refactor(generate) Fix --package-dir flags. Clean up

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -31,35 +31,45 @@ readonly SCRIPT_ARGS="${@}"
 # TODO: Separate manual from usage. Also, auto generate exit codes.
 function usage() {
   cat << EOF
-${SCRIPT_NAME}
+${SCRIPT_NAME} ${EZ_VERSION}
 
-  Universal BASH package installer purely written in bash scripts.
+NAME:
 
+  ez - Universal Bash package installer purely written in bash scripts.
 
 USAGE:
 
-  $(basename -- ${SCRIPT_PATH}) [-h] [-V] [-jvxyRS] [-o destination] [-p package-dir] package1 package2 ...
-
+  $SCRIPT_NAME [options] package1 package2 ...
 
 OPTIONS:
 
-  --package-dir   -D    Directory to search packages from.
-                        Global default=$PACKAGE_ROOT_DIR.
-                        Local default=$LOCAL_PACKAGE_ROOT_DIR.
-  --generate      -g    Generate package(s) locally instead.
-  --json          -j    Parse package data as json.
-  --destination   -o    Package output directory (for curl, wget, etc.).
-                        default=$HOME/Downloads.
-  --no-norecurse  -R    Prevent recursive package dependency installation.
-  --as-root       -S    Run package manager as root (sudo).
+  Flag option with arguments
 
-  --quiet         -q    Suppress standard output. LOG_DEBUG_LEVEL=3.
-  --debug         -x    Debug mode (print all log levels). LOG_DEBUG_LEVEL=7.
-  --skip-confirm  -y    Skip confirmation.
-  --help          -h    Print usage.
-  --version       -V    Print ez version.
+    --package-dir   -D    Directory to search packages from.
+                          Global default=\$PACKAGE_ROOT_DIR.
+                          Local default=\$LOCAL_PACKAGE_ROOT_DIR.
+    --destination   -o    Package output directory (for curl, wget, etc.).
+                          default=\$HOME/Downloads.
+
+  Flag option switches
+
+    --generate      -g    Generate package(s) instead of install.
+    --json          -j    Parse package data as json.
+    --no-norecurse  -R    Prevent recursive package dependency installation.
+    --as-root       -S    Run package manager as root (sudo).
+
+    --quiet         -q    Suppress standard output. LOG_DEBUG_LEVEL=3.
+    --debug         -x    Debug mode (print all log levels). LOG_DEBUG_LEVEL=7.
+    --skip-confirm  -y    Skip confirmation.
+    --help          -h    Print usage.
+    --version       -V    Print ez version.
+
+EOF
+}
 
 
+function manual () {
+  cat << EOF
 EXIT CODES:
 
   Ez Special Exit Codes
@@ -148,7 +158,7 @@ function handle_args() {
   while getopts "D:o:gjqRSxyhV" opt; do
     case ${opt} in
       D)
-        PACKAGE_DIR="${OPTARG}"
+        LOCAL_PACKAGE_ROOT_DIR="${OPTARG}"
         ;;
       o)
         DESTINATION="${OPTARG}"
@@ -177,24 +187,28 @@ function handle_args() {
         SKIP_CONFIRM=true
         ;;
       h)
-        usage; exit $BASH_EX_OK
+        usage; manual; exit $BASH_EX_OK
         ;;
       V)
         echo "${SCRIPT_NAME} ${VERSION}"; exit $BASH_EX_OK
         ;;
+      *)
+        usage
+        error "Invalid flag option(s)"
+        exit $BASH_SYS_EX_USAGE
     esac
   done
   shift "$((OPTIND-1))"
 
   if [[ -p /dev/stdin ]]; then
+    usage
     error "Piped arguments not supported"
-    usage;
     exit $BASH_SYS_EX_USAGE
   fi
 
   if [[ ! -t 0 && ! -p /dev/stdin ]]; then
+    usage
     error "Stdin redirection not supported"
-    usage;
     exit $BASH_SYS_EX_USAGE
   fi
 
@@ -203,6 +217,7 @@ function handle_args() {
     if [[ -n "${@+x}" ]]; then
       IFS=" " read -a PACKAGES <<< "${@}"
     else
+      usage
       error "No package(s) provided"
       exit $BASH_SYS_EX_USAGE
     fi
@@ -235,8 +250,12 @@ function _ctrl_c() {
 
 
 function _main () {
+  local res=0
+
   script_vars
   handle_args "${SCRIPT_ARGS}"
+  res=$?
+  [[ $res -ne $BASH_EX_OK ]] && return $res
 
   # Set up trap
   if "${DEBUG}"; then
@@ -250,8 +269,6 @@ function _main () {
     batch_generate_package ${packages[@]}
   else
     ! ${DEBUG} && echo -e "About to install the following packages:\n"
-
-    local res=0
 
     # TODO: Fully support json configs
     if ! $JSON; then
diff --git a/generate/ez-gen b/generate/ez-gen
--- a/generate/ez-gen
+++ b/generate/ez-gen
@@ -9,12 +9,14 @@ source "${EZ_INSTALL_HOME}/common/include.sh"
 ###################################################### EXTERNAL DEPENDENCIES ###
 
 include "${EZ_INSTALL_HOME}/common/common.sh"
+include "${EZ_INSTALL_HOME}/generate/generate.sh"
 include "${EZ_INSTALL_HOME}/install/common.sh"
 include "${EZ_INSTALL_HOME}/install/const.sh"
 include "${EZ_INSTALL_HOME}/install/utils/actions.sh"
 
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
+readonly EZ_GEN_VERSION="0.3 BETA"
 readonly SCRIPT_ARGS="${@}"
 
 ############################################################### FLAG OPTIONS ###
@@ -23,15 +25,15 @@ function usage() {
   local scriptpath="$(realpath -- "${0}")"
 
 cat <<- EOF
-$(basename -- "${scriptpath}")
+${SCRIPT_NAME} ${EZ_GEN_VERSION}
 
-  Package generator for ez, a universal BASH package installer.
+NAME:
 
+  ez-gen - package generator for ez-install, a universal Bash package installer.
 
 USAGE:
 
-  ./$(basename -- "${scriptpath}") [-h] [-euvxy] package
-
+  ${SCRIPT_NAME} [options] package
 
 OPTIONS:
 
@@ -41,27 +43,31 @@ OPTIONS:
     --command-name     -c    Package executable name.
     --dependency       -d    Package installation dependencies.
     --package-dir      -D    Directory to generate packages to.
-                            default=$LOCAL_PACKAGE_DIR.
+                             default=\$LOCAL_PACKAGE_ROOT_DIR.
+                             global=\$PACKAGE_ROOT_DIR.
     --global           -G    Generate to global generate package directory.
-                            Overrides '--package-dir'.
-    --package-manager  -m    Package manager installer.
+                             Overrides '--package-dir'.
+    --package-manager  -m    Package manager installer. '--package-name' is
+                             required for curl, wget, and git.
     --package-name     -n    Package filename.
     --destination      -o    Package output directory (for curl, wget, etc.).
-                            default=$HOME/Downloads.
+                             default=\$HOME/Downloads.
 
   Flag option switches
 
+    --interactive      -i    Run interactive mode.
     --pre              -p    Generate package pre installation.
     --post             -P    Generate package post installation.
     --skip-main        -S    Skip main package generation. Requires --pre and/or
-                            --post flag(s) to be active.
+                             --post flag(s) to be active.
     --execute          -e    Pipe package with \`| sh\` to execute. (for curl, wget).
     --update           -u    Update package manager repository before installation
-                            (for apt, pkg, etc.).
+                             (for apt, pkg, etc.).
     --quiet            -q    Suppress standard output. LOG_DEBUG_LEVEL=3.
     --debug            -x    Debug mode (print all log levels). LOG_DEBUG_LEVEL=7.
     --skip-confirm     -y    Skip confirmation.
     --help             -h    Print usage.
+    --version          -V    Print ez-gen version.
 
 EOF
 }
@@ -80,6 +86,7 @@ function handle_args() {
       --package-manager)  args="${args:-}-m ";;
       --package-name)     args="${args:-}-n ";;
       --destination)      args="${args:-}-o ";;
+      --interactive)      args="${args:-}-i ";;
       --pre)              args="${args:-}-p ";;
       --post)             args="${args:-}-P ";;
       --quiet)            args="${args:-}-q ";;
@@ -89,6 +96,7 @@ function handle_args() {
       --update)           args="${args:-}-u ";;
       --debug)            args="${args:-}-x ";;
       --help)             args="${args:-}-h ";;
+      --version)          args="${args:-}-V ";;
       *)
         # Don't work with OPTARG with spaces
         # [[ "${arg:0:1}" == "-" ]] || delim="\""
@@ -114,7 +122,9 @@ function handle_args() {
   PACKAGE_MANAGER=""
   PACKAGE_NAME=""
   DESTINATION=""
+  GEN_PACKAGE_ROOT_DIR=""
   GEN_PACKAGE_DIR=""
+  INTERACTIVE=false
   GENERATE_PRE=false
   GENERATE_POST=false
   SKIP_MAIN=false
@@ -124,7 +134,7 @@ function handle_args() {
   UPDATE=false
 
   OPTIND=1
-  while getopts "a:A:c:d:D:m:n:o:pPeuGqSxyh" opt; do
+  while getopts "a:A:c:d:D:m:n:o:ipPeuGqSxyhV" opt; do
     case ${opt} in
       a)
         ARGS="${OPTARG}"
@@ -139,7 +149,7 @@ function handle_args() {
         DEPENDENCIES="${OPTARG}"
         ;;
       D)
-        GEN_PACKAGE_DIR="${OPTARG}"
+        GEN_PACKAGE_ROOT_DIR="${OPTARG}"
         ;;
       m)
         PACKAGE_MANAGER="$(echo "${OPTARG}" | awk '{print tolower($0)}')"
@@ -149,6 +159,9 @@ function handle_args() {
         ;;
       o)
         DESTINATION="${OPTARG}"
+        ;;
+      i)
+        INTERACTIVE=true
         ;;
       p)
         GENERATE_PRE=true
@@ -185,32 +198,48 @@ function handle_args() {
       h)
         usage; exit 0
         ;;
+      V)
+        echo "${SCRIPT_NAME} ${VERSION}"; exit $BASH_EX_OK
+        ;;
+      *)
+        usage
+        error "Invalid flag option(s)"
+        exit $BASH_SYS_EX_USAGE
     esac
   done
   shift "$((OPTIND-1))"
 
-  if [[ -z "${@+x}" ]] && [[ "${PACKAGE_MANAGER}" != "local" ]]; then
+  if ! $INTERACTIVE && [[ -z "${1+x}" ]] && [[ "${PACKAGE_MANAGER}" != "local" ]]; then
+    usage
     error "${BASH_SYS_MSG_USAGE_MISSARG}"
     exit $BASH_SYS_EX_USAGE
   fi
 
-  PACKAGE="${@:-${PACKAGE_NAME}}"
+  resolve_package_dir
+
+  PACKAGE="${1:-${PACKAGE_NAME}}"
   PACKAGE_NAME="${PACKAGE_NAME:-${PACKAGE}}"
   COMMAND_NAME="${COMMAND_NAME:-${PACKAGE_NAME}}"
   FILE="${PACKAGE_NAME:-${PACKAGE}}"
 
   if [[ ${PACKAGE_MANAGER} == "curl" ]] || [[ ${PACKAGE_MANAGER} == "wget" ]] || [[ ${PACKAGE_MANAGER} == "git" ]]; then
     if [[ -z "${PACKAGE_NAME}" ]]; then
+      usage
       error "No package name provided for '${PACKAGE_MANAGER} ${PACKAGE}'"
       exit $BASH_SYS_EX_USAGE
     fi
   fi
 
-  resolve_package_dir
   if $GLOBAL; then
+    GEN_PACKAGE_ROOT_DIR="${PACKAGE_ROOT_DIR}"
     GEN_PACKAGE_DIR="${PACKAGE_DIR}"
-  elif [[ -z "${GEN_PACKAGE_DIR}" ]]; then
+  elif [[ -z "${GEN_PACKAGE_ROOT_DIR}" ]]; then
+    GEN_PACKAGE_ROOT_DIR="${LOCAL_PACKAGE_ROOT_DIR}"
     GEN_PACKAGE_DIR="${LOCAL_PACKAGE_DIR}"
+  else
+    local distrib_id="${OS_DISTRIB_ID}"; to_lower distrib_id
+    local distrib_release="${OS_DISTRIB_RELEASE}"
+    GEN_PACKAGE_DIR="${GEN_PACKAGE_ROOT_DIR}/${distrib_id}/${distrib_release}"
   fi
 
   return $BASH_EX_OK
@@ -219,8 +248,12 @@ function handle_args() {
 ######################################################## FUNCTION DEFINITION ###
 
 function check_package() {
+  if [[ -z "${1+x}" ]]; then
+    error "${BASH_SYS_MSG_USAGE_MISSARG}"
+    return $BASH_SYS_EX_USAGE
+  fi
+
   local package="${1:-}"
-  local prompt="${2:-Do you wish to continue? (Y/y): }"
 
   if [[ -z "${@+x}" ]]; then
     error "${BASH_SYS_MSG_USAGE_MISSARG}"
@@ -228,7 +261,7 @@ function check_package() {
   fi
 
   if [[ -e "${package}" ]] && ! $SKIP_CONFIRM; then
-    confirm "'${package}' already exists. ${prompt}" || return $BASH_EZ_EX_PAC_EXIST
+    confirm "'${package}' already exist. Continue? (Y/y): " || return $BASH_EZ_EX_PAC_EXIST
   fi
 }
 
@@ -257,7 +290,7 @@ function give_exec_permission() {
 }
 
 
-function generate_package_template() {
+function generate_template_main() {
   if [[ -z "${1+x}" ]]; then
     error "${BASH_SYS_MSG_USAGE_MISSARG}"
     return $BASH_SYS_EX_USAGE
@@ -342,43 +375,58 @@ function generate_template_post() {
 function _main() {
   local res=0
 
+  script_vars
   handle_args "${SCRIPT_ARGS}"
   res=$?
   [[ $res -ne $BASH_EX_OK ]] && return $res
 
-  if [[ -z "${PACKAGE_MANAGER}" ]]; then
-    local file_path="${GEN_PACKAGE_DIR}/${FILE}"
-  else
-    local file_path="${GEN_PACKAGE_DIR}/${FILE}.${PACKAGE_MANAGER}"
-  fi
+  if $INTERACTIVE; then
+    local main=""
+    local pre=""
+    local post=""
+    prompt_boolean main "Generate main package? (true/false): "
+    prompt_boolean pre "Generate pre package? (true/false) "
+    prompt_boolean post "Generate post package? (true/false) "
 
-  if [[ ! -d "${GEN_PACKAGE_DIR}" ]]; then
-    if execlog "mkdir -p '${GEN_PACKAGE_DIR}'"; then
-      ok "'${GEN_PACKAGE_DIR}' directory created"
+    $main && i_generate_template_main -D "${GEN_PACKAGE_ROOT_DIR}" "${PACKAGE}"
+    $pre && i_generate_template_pre -D "${GEN_PACKAGE_ROOT_DIR}" "${PACKAGE}"
+    $post && i_generate_template_post -D "${GEN_PACKAGE_ROOT_DIR}" "${PACKAGE}"
+  else
+    if [[ -z "${PACKAGE_MANAGER}" ]]; then
+      local file_path="${GEN_PACKAGE_DIR}/${FILE}"
     else
-      res=$?
-      error "'${GEN_PACKAGE_DIR}' creation failed"
-      return $BASH_SYS_EX_CANTCREAT
+      local file_path="${GEN_PACKAGE_DIR}/${FILE}.${PACKAGE_MANAGER}"
     fi
-  fi
 
-  local continue=""
-  if $GENERATE_PRE || $GENERATE_POST; then
-    if ! $SKIP_MAIN && confirm "Would you like to generate the main package template? (Y/y): "; then
-      generate_package_template "${file_path}"
-      res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
+    if [[ ! -d "${GEN_PACKAGE_DIR}" ]]; then
+      if execlog "mkdir -p '${GEN_PACKAGE_DIR}'"; then
+        ok "'${GEN_PACKAGE_DIR}' directory created"
+      else
+        res=$?
+        error "'${GEN_PACKAGE_DIR}' creation failed"
+        return $BASH_SYS_EX_CANTCREAT
+      fi
     fi
-    if $GENERATE_PRE; then
-      generate_template_pre "${file_path}"
-      res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
+
+    local continue=""
+    if $GENERATE_PRE || $GENERATE_POST; then
+      if ! $SKIP_MAIN && confirm "Would you like to generate the main package template? (Y/y): "; then
+        generate_template_main "${file_path}"
+        res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
+      fi
+      if $GENERATE_PRE; then
+        generate_template_pre "${file_path}"
+        res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
+      fi
+      if $GENERATE_POST; then
+        generate_template_post "${file_path}"
+        res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
+      fi
+    else
+      generate_template_main "${file_path}"
+      res=$?
     fi
-    if $GENERATE_POST; then
-      generate_template_post "${file_path}"
-      res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
-    fi
-  else
-    generate_package_template "${file_path}"
-    res=$?
+    finish "Package generated to ${file_path}"
   fi
   return $res
 }
