feat(install) Finish generate feature for ez -g

diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -18,10 +18,12 @@ include "${EZ_INSTALL_HOME}/install/utils/pac-transform.sh"
 include "${EZ_INSTALL_HOME}/install/pac-install.sh"
 include "${EZ_INSTALL_HOME}/install/install.sh"
 include "${EZ_INSTALL_HOME}/install/common.sh"
+include "${EZ_INSTALL_HOME}/generate/generate.sh"
 
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
 readonly EZ_VERSION="0.3-beta"
+readonly EZ_SUPPORTED_PACKAGE_MANAGER='apt apt-add npm pip pip2 pip3 pkg curl wget git local'
 readonly LOG_SYSLOG=true
 readonly LOG_FILELOG=true
 readonly SCRIPT_ARGS="${@}"
@@ -147,7 +149,7 @@ function handle_args() {
   OPTIND=1
   while getopts "gjo:p:RSvxyhV" opt; do
     case ${opt} in
-      j)
+      g)
         GENERATE=true
         ;;
       j)
@@ -258,44 +260,48 @@ function _main () {
   local -a packages=( ${PACKAGES[@]} )
   array_unique packages
 
-  ! ${DEBUG} && echo -e "About to install the following packages:\n"
+  if $GENERATE; then
+    batch_generate_package ${packages[@]}
+  else
+    ! ${DEBUG} && echo -e "About to install the following packages:\n"
 
-  local res=0
+    local res=0
 
-  # TODO: Fully support json configs
-  if ! $JSON; then
-    validate_packages ${packages[@]}
-    res=$?; [[ ${res} -ne $BASH_EX_OK ]] && return $res
+    # TODO: Fully support json configs
+    if ! $JSON; then
+      validate_packages ${packages[@]}
+      res=$?; [[ ${res} -ne $BASH_EX_OK ]] && return $res
 
-    echo "Jsonifying..."
-    pac_array_jsonify -R $RECURSIVE -S $AS_ROOT -- packages
-  fi
-
-  if $DEBUG && $VERBOSE || $JSON; then
-    local jq="${EZ_INSTALL_HOME}/lib/parser/jq"
-
-    if [[ ! -e "${jq}" ]]; then
-      error "Missing ${jq} dependency"
-      return $BASH_EZ_EX_DEP_NOTFOUND
+      echo "Jsonifying..."
+      pac_array_jsonify -R $RECURSIVE -S $AS_ROOT -- packages
     fi
 
-    # echo "${packages[@]}"
-    for package in ${packages[@]}; do
-      echo "${package}" | ${jq} -r ".package"
-    done
+    if $DEBUG && $VERBOSE || $JSON; then
+      local jq="${EZ_INSTALL_HOME}/lib/parser/jq"
+
+      if [[ ! -e "${jq}" ]]; then
+        error "Missing ${jq} dependency"
+        return $BASH_EZ_EX_DEP_NOTFOUND
+      fi
+
+      # echo "${packages[@]}"
+      for package in ${packages[@]}; do
+        echo "${package}" | ${jq} -r ".package"
+      done
+    fi
+
+    confirm "You are about to install the package(s) above. Continue? (Y/y): " \
+      || exit $BASH_EX_GENERAL
+
+    warning "Installation in progress... Do not interrupt!"
+
+    pac_batch_json_install "${packages[@]}"
+    res=$?; [[ $res -ne $BASH_EX_OK ]] && exit $res
+
+    [[ -n "${packages+x}" ]] && pac_report
   fi
 
-  confirm "You are about to install the package(s) above. Continue? (Y/y): " \
-    || exit $BASH_EX_GENERAL
-
-  warning "Installation in progress... Do not interrupt!"
-
-  pac_batch_json_install "${packages[@]}"
-  res=$?; [[ $res -ne $BASH_EX_OK ]] && exit $res
-
-  [[ -n "${packages+x}" ]] && pac_report
-
-  finish "Installation finished!"
+  finish "Finished!"
   return $BASH_EX_OK
 }
 
