fix(gen/install): Fix argument and flag handling
- ez now supports POSIX style flags
  - e.g. --flag=optarg
  - e.g. -f optarg
  - e.g. -f='opt arg'
  - e.g. --flag 'opt arg'
- Fix OPTARG whitespace handling
  - ez pass on arguments as string to gen and install to preserve quotes and
    whitespaces
- Improve gen interactive mode and overall argument handling
- Update generate templates
- Some minor fixes

diff --git a/generate/gen b/generate/gen
--- a/generate/gen
+++ b/generate/gen
@@ -18,7 +18,8 @@ include "${EZ_INSTALL_HOME}/actions.sh"
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
 readonly EZ_GEN_VERSION="0.3 BETA"
-readonly SCRIPT_ARGS="${@}"
+readonly SCRIPT_ARGS="$@"
+readonly SCRIPT_ARGS_NUM=$#
 
 ############################################################### FLAG OPTIONS ###
 
@@ -40,7 +41,8 @@ GEN OPTIONS:
 
   Flag option with arguments
 
-    --author           -a    Package author.
+    --args             -a    Package manager arguments.
+    --author           -A    Package author.
     --command-name     -c    Package executable name.
     --dependency       -d    Package installation dependencies.
     --package-dir      -D    Directory to generate packages to.
@@ -82,49 +84,6 @@ EOF
 
 
 function handle_args() {
-  local arg=
-  for arg in ${@}; do
-    local delim=""
-    case "${arg}" in
-      --author)           args="${args:-}-a ";;
-      --command-name)     args="${args:-}-c ";;
-      --dependency)       args="${args:-}-d ";;
-      --package-dir)      args="${args:-}-D ";;
-      --execute)          args="${args:-}-e ";;
-      --no-execute)       args="${args:-}-E ";;
-      --force)            args="${args:-}-f ";;
-      --no-force)         args="${args:-}-F ";;
-      --package-manager)  args="${args:-}-m ";;
-      --package-name)     args="${args:-}-n ";;
-      --destination)      args="${args:-}-o ";;
-      --global)           args="${args:-}-G ";;
-      --interactive)      args="${args:-}-i ";;
-      --skip-main)        args="${args:-}-M ";;
-      --pre)              args="${args:-}-p ";;
-      --post)             args="${args:-}-P ";;
-      --quiet)            args="${args:-}-q ";;
-      --as_root)          args="${args:-}-s ";;
-      --no_root)          args="${args:-}-S ";;
-      --skip-edit)        args="${args:-}-t ";;
-      --update)           args="${args:-}-u ";;
-      --no-update)        args="${args:-}-U ";;
-      --debug)            args="${args:-}-x ";;
-      --skip-confirm)     args="${args:-}-y ";;
-      --no-colors)        args="${args:-}-z ";;
-      --help)             args="${args:-}-h ";;
-      --version)          args="${args:-}-V ";;
-      *)
-        # Don't work with OPTARG with spaces
-        # [[ "${arg:0:1}" == "-" ]] || delim="\""
-        # args="${args:-}${delim}${arg}${delim} ";;
-
-        # Do not surround with " to allow OPTARG with '\ '
-        args="${args:-} ${arg}";;
-    esac
-  done
-
-  eval set -- ${args:-}
-
   [[ -z "${SKIP_CONFIRM+x}" ]]    && SKIP_CONFIRM=false
   [[ -z "${VERBOSE+x}" ]]         && VERBOSE=true
   [[ -z "${DEBUG+x}" ]]           && DEBUG=false
@@ -141,11 +100,11 @@ function handle_args() {
   GEN_PACKAGE_ROOT_DIR=""
   GEN_PACKAGE_DIR=""
   INTERACTIVE=false
+  GENERATE_MAIN=true
   GENERATE_PRE=false
   GENERATE_POST=false
   AS_ROOT=false
   ALLOW_DEP_FAIL=false
-  SKIP_MAIN=false
   SKIP_EDIT=false
   EXECUTE=false
   FORCE=false
@@ -154,36 +113,114 @@ function handle_args() {
 
   CONFIG=""
 
-  OPTIND=1
-  while getopts "a:A:c:d:m:n:o:eEfFsSuUwWD:GiMpPtqxyzhV" opt; do
-    case ${opt} in
+  #== parse options ==#
+  # Ref: https://www.uxora.com/unix/shell-script/22-handle-long-options-with-getopts
+
+  # Especially useful when relaying script args with group quoted OPTARG
+  eval set -- ${@:-}
+
+  local -A long_opts_map
+  long_opts_map=(
+    ['args']=a
+    ['author']=A
+    ['command-name']=c
+    ['dependency']=d
+    ['package-dir']=D
+    ['execute']=e
+    ['no-execute']=E
+    ['force']=f
+    ['no-force']=F
+    ['package-manager']=m
+    ['package-name']=n
+    ['destination']=o
+    ['global']=G
+    ['interactive']=i
+    ['skip-main']=M
+    ['pre']=p
+    ['post']=P
+    ['quiet']=q
+    ['as_root']=s
+    ['no_root']=S
+    ['skip-edit']=t
+    ['update']=u
+    ['no-update']=U
+    ['debug']=x
+    ['skip-confirm']=y
+    ['no-colors']=z
+    ['help']=h
+    ['version']=V
+  )
+
+  local script_opts=':a:A:c:d:m:n:o:D:eEfFsSuUwWGiMpPtqxyzhV-:'
+  local script_args="$@"
+  local script_args_num=$#
+
+  local OPTIND=1
+  while getopts ${script_opts} OPTION; do
+    #== translate long options to short ==#
+    if [[ "x$OPTION" == "x-" ]]; then
+      LONG_OPTION=$OPTARG
+      LONG_OPTARG=$(echo $LONG_OPTION | grep "=" | cut -d'=' -f2)
+      LONG_OPTIND=-1
+
+      [[ "x$LONG_OPTARG" = "x" ]] && LONG_OPTIND=$OPTIND || LONG_OPTION=$(echo $OPTARG | cut -d'=' -f1)
+      [[ $LONG_OPTIND -ne -1 ]] && eval LONG_OPTARG="\$$LONG_OPTIND"
+
+      OPTION=${long_opts_map[$LONG_OPTION]}
+      [[ "x$OPTION" = "x" ]] &&  OPTION="?" OPTARG="-$LONG_OPTION"
+
+      if [[ $( echo "${script_opts}" | grep -c "${OPTION}:" ) -eq 1 ]]; then
+        # OPTION followed by another option instead of argument will be omitted.
+        if [[ "x${LONG_OPTARG}" = "x" ]] || [[ "${LONG_OPTARG}" = -* ]] \
+           && [[ "x${OPTION}" != 'xa' ]]; then  # Do not omit 'a' flag
+          OPTION=":" OPTARG="-$LONG_OPTION"
+        else
+          OPTARG="$LONG_OPTARG";
+          if [[ $LONG_OPTIND -ne -1 ]]; then
+            [[ $OPTIND -le $script_args_num ]] && OPTIND=$(( $OPTIND+1 ))
+            shift $OPTIND
+            OPTIND=1
+          fi
+        fi
+      fi
+    fi
+
+    # OPTION followed by another option instead of argument will be omitted.
+    if [[ "x${OPTION}" != "x:" ]] && [[ "x${OPTION}" != "x?" ]] && [[ "${OPTARG:-}" = -* ]] \
+       && [[ "x${OPTION}" != 'xa' ]]; then  # Do not omit 'a' flag
+      OPTARG="$OPTION" OPTION=":"
+    fi
+
+    #== manage options ==#
+    case "$OPTION" in
       # For single package
-      a) ARGS="${OPTARG}";;
-      c) COMMAND_NAME="${OPTARG}";;
-      d) DEPENDENCIES="${OPTARG}";;
-      n) PACKAGE_NAME="${OPTARG}";;
-      # Inherited by multiple packages
-      A) AUTHOR="${OPTARG}";          CONFIG="${CONFIG} -${opt} ${OPTARG}" ;;
-      m) PACKAGE_MANAGER="${OPTARG}"; CONFIG="${CONFIG} -${opt} ${OPTARG}" ;;
-      o) DESTINATION="${OPTARG}";     CONFIG="${CONFIG} -${opt} ${OPTARG}" ;;
-      # TODO: Add in-line package opts for flag switches
-      e) EXECUTE=true;                CONFIG="${CONFIG} -${opt}" ;;
-      E) EXECUTE=false;               CONFIG="${CONFIG} -${opt}" ;;
-      e) FORCE=true;                  CONFIG="${CONFIG} -${opt}" ;;
-      E) FORCE=false;                 CONFIG="${CONFIG} -${opt}" ;;
-      s) AS_ROOT=true;                CONFIG="${CONFIG} -${opt}" ;;
-      S) AS_ROOT=false;               CONFIG="${CONFIG} -${opt}" ;;
-      u) UPDATE=true;                 CONFIG="${CONFIG} -${opt}" ;;
-      U) UPDATE=false;                CONFIG="${CONFIG} -${opt}" ;;
-      w) ALLOW_DEP_FAIL=true;         CONFIG="${CONFIG} -${opt}" ;;
-      W) ALLOW_DEP_FAIL=false;        CONFIG="${CONFIG} -${opt}" ;;
-      D) GEN_PACKAGE_ROOT_DIR="${OPTARG}" ;;
-      G) GLOBAL=true ;;
-      i) INTERACTIVE=true ;;
-      M) SKIP_MAIN=true ;;
+      a) ARGS=${OPTARG} ;;
+      c) COMMAND_NAME=${OPTARG} ;;
+      d) DEPENDENCIES=${OPTARG} ;;
+      n) PACKAGE_NAME=${OPTARG} ;;
+      # Inherited by all packages but can be overridden by file extension
+      m) PACKAGE_MANAGER=${OPTARG} ;;
+      M) GENERATE_MAIN=false ;;
       p) GENERATE_PRE=true ;;
       P) GENERATE_POST=true ;;
-      t) SKIP_EDIT=true ;;
+      # Inherited by all packages
+      A) AUTHOR=${OPTARG};          CONFIG="${CONFIG} -${OPTION} '${OPTARG}'" ;;
+      o) DESTINATION=${OPTARG} ;;
+      # TODO: Add in-line package opts for flag switches
+      e) EXECUTE=true;              CONFIG="${CONFIG} -${OPTION}" ;;
+      E) EXECUTE=false;             CONFIG="${CONFIG} -${OPTION}" ;;
+      e) FORCE=true;                CONFIG="${CONFIG} -${OPTION}" ;;
+      E) FORCE=false;               CONFIG="${CONFIG} -${OPTION}" ;;
+      s) AS_ROOT=true;              CONFIG="${CONFIG} -${OPTION}" ;;
+      S) AS_ROOT=false;             CONFIG="${CONFIG} -${OPTION}" ;;
+      u) UPDATE=true;               CONFIG="${CONFIG} -${OPTION}" ;;
+      U) UPDATE=false;              CONFIG="${CONFIG} -${OPTION}" ;;
+      w) ALLOW_DEP_FAIL=true;       CONFIG="${CONFIG} -${OPTION}" ;;
+      W) ALLOW_DEP_FAIL=false;      CONFIG="${CONFIG} -${OPTION}" ;;
+      t) SKIP_EDIT=true;            CONFIG="${CONFIG} -${OPTION}" ;;
+      D) GEN_PACKAGE_ROOT_DIR=${OPTARG} ;;
+      G) GLOBAL=true ;;
+      i) INTERACTIVE=true ;;
       q) VERBOSE=false; LOG_DEBUG_LEVEL=3 ;;
       x) DEBUG=true; LOG_DEBUG_LEVEL=7 ;;
       y) SKIP_CONFIRM=true ;;
@@ -191,19 +228,18 @@ function handle_args() {
         ENABLE_COLORS=false
         include "${EZ_INSTALL_HOME}/common/colors.sh"
         ;;
-      h)
-        usage; exit 0
-        ;;
-      V)
-        echo "${SCRIPT_NAME} ${EZ_GEN_VERSION}"; exit $BASH_EX_OK
-        ;;
+      h) usage; exit 0 ;;
+      V) echo "${SCRIPT_NAME} ${EZ_GEN_VERSION}"; exit $BASH_EX_OK ;;
+      \?) echo "An invalid option has been entered: ${OPTARG:-}" ;;
+      :) echo "The additional argument for option ${OPTARG:-} was omitted." ;;
       *)
         usage
         error "Invalid flag option(s)"
         exit $BASH_SYS_EX_USAGE
     esac
   done
-  shift "$((OPTIND-1))"
+  shift $((${OPTIND} - 1))
+
 
   if ! $INTERACTIVE && [[ -z "${@+x}" ]] && [[ "${PACKAGE_MANAGER}" != "local" ]]; then
     usage
@@ -216,7 +252,7 @@ function handle_args() {
   if [[ ${PACKAGE_MANAGER} == "curl" ]] || [[ ${PACKAGE_MANAGER} == "wget" ]] || [[ ${PACKAGE_MANAGER} == "git" ]]; then
     if [[ -z "${PACKAGE_NAME}" ]]; then
       usage
-      error "No package name provided for '${PACKAGE_MANAGER} ${1}'"
+      error "Package name required for '${PACKAGE_MANAGER}'"
       exit $BASH_SYS_EX_USAGE
     fi
   fi
@@ -228,7 +264,7 @@ function handle_args() {
       readonly PACKAGES
     else
       usage
-      error "No package(s) provided"
+      error "No package(s) provided. Provide at least one"
       exit $BASH_SYS_EX_USAGE
     fi
   fi
@@ -254,56 +290,105 @@ function _main() {
   local res=0
 
   script_vars
-  handle_args "${SCRIPT_ARGS}"
+  handle_args "$@"
   res=$?
   [[ $res -ne $BASH_EX_OK ]] && return $res
 
   local -a packages=( ${PACKAGES[@]} )
   array_unique packages
 
-  for package in ${packages[@]}; do
-    local config="${CONFIG}"
+  for package_full in ${packages[@]}; do
+    # TODO: In-line opts config
+    parse_inline_opts "${package_full}"
+    package_full="${package_full%#*}" # Strip #opts
+
+    local package_manager=""
+    local hook=""
+    local package=""
     local args=""
     local command_name=""
     local dependencies=""
     local package_name=""
+    local generate_main=${GENERATE_MAIN:-true}
+    local generate_pre=${GENERATE_PRE:-false}
+    local generate_post=${GENERATE_POST:-false}
+    local config="${CONFIG}"
+    local config_hook="${CONFIG}"
 
+    if is_package_manager_downloader "${PACKAGE_MANAGER}" || [[ "${PACKAGE_MANAGER}" == 'apt-add' ]]; then
+      package_manager="${PACKAGE_MANAGER}"
+      package="${package_full}"
+    elif is_package_ppa "${package_full}"; then
+      package_manager="apt-add"
+      package="${package_full}"
+    else
+      # Ref: https://unix.stackexchange.com/a/241282
+      package_manager="$(sed -n "s/^.*\.\(${EZ_SUPPORTED_PACKAGE_MANAGER// /\\.\\?\\|}\).*/\1/p" <<< "${package_full}")"
+      package="$(sed "s/\.\(${EZ_SUPPORTED_PACKAGE_MANAGER// /\\.\\?\\|}\)\?\(\.pre\|\.post\)\?$//" <<< "${package_full}")"
+      hook="$(sed -n "s/^.*\.\(pre\|post\)$/\1/p" <<< "${package_full}")"
+    fi
+
+    [[ -z "${package_manager}" ]] && package_manager="${PACKAGE_MANAGER}"
+    to_lower package_manager
+
+    # Skip main template generation when hook detected
+    if [[ "${hook}" == 'pre' ]]; then
+      generate_pre=true
+      generate_main=false
+    elif [[ "${hook}" == 'post' ]]; then
+      generate_post=true
+      generate_main=false
+    fi
+
+    # Some configs may only apply on single package generation
     if [[ ${#PACKAGES[@]} -eq 1 ]]; then
       args="${ARGS}"
       command_name="${COMMAND_NAME}"
       dependencies="${DEPENDENCIES}"
+      destination="${DESTINATION}"
       package_name="${PACKAGE_NAME:-${package}}"
     else
+      destination="${DESTINATION}"
       package_name="${package}"
     fi
 
-    [[ -n "${args}" ]]         && config="${config} -a ${args}"
-    [[ -n "${command_name}" ]] && config="${config} -c ${command_name}"
-    [[ -n "${dependencies}" ]] && config="${config} -d ${dependencies}"
-    [[ -n "${package}" ]]      && config="${config} -p ${package}"
-    [[ -n "${package_name}" ]] && config="${config} -n ${package_name}"
-    ${SKIP_EDIT}               && config="${config} -t"
+    [[ -n "${args}" ]]            && config="${config} -a '${args}'"
+    [[ -n "${command_name}" ]]    && config="${config} -c '${command_name}'"
+    [[ -n "${dependencies}" ]]    && config="${config} -d '${dependencies}'"
+    [[ -n "${package}" ]]         && config="${config} -p '${package}'"
+    [[ -n "${package_name}" ]]    && config="${config} -n '${package_name}'"
+    [[ -n "${package_manager}" ]] && config="${config} -m '${package_manager}'"
+    [[ -n "${destination}" ]]     && config="${config} -o '${destination}'"
+    ${SKIP_EDIT}                  && config="${config} -t"
+
+    [[ -n "${package}" ]]         && config_hook="${config_hook} -p '${package}'"
+    [[ -n "${package_name}" ]]    && config_hook="${config_hook} -n '${package_name}'"
+    [[ -n "${package_manager}" ]] && config_hook="${config_hook} -m '${package_manager}'"
+    ${SKIP_EDIT}                  && config_hook="${config_hook} -t"
+
+    # Resolve filepath
+    if [[ -z "${package_manager}" ]]; then
+      local file_path="${GEN_PACKAGE_DIR}/${package_name}"
+    else
+      local file_path="${GEN_PACKAGE_DIR}/${package_name}.${package_manager}"
+    fi
 
     if $INTERACTIVE; then
-      local main="true"
-      local pre=""
-      local post=""
+      warning "Entering interactive template generation for '${package}'..."
 
-      warning "Generating ${package}"
-      ! $SKIP_MAIN && prompt_boolean main "Generate main package (default=true)? "
-      prompt_boolean pre "Generate pre package (default=false)? "
-      prompt_boolean post "Generate post package (default=false)? "
-
-      $main && i_generate_template_main -D "${GEN_PACKAGE_DIR}" -t ${SKIP_EDIT} "${package}"
-      $pre  && i_generate_template_pre  -D "${GEN_PACKAGE_DIR}" -t ${SKIP_EDIT} "${package}"
-      $post && i_generate_template_post -D "${GEN_PACKAGE_DIR}" -t ${SKIP_EDIT} "${package}"
-    else
-      if [[ -z "${PACKAGE_MANAGER}" ]]; then
-        local file_path="${GEN_PACKAGE_DIR}/${package_name}"
+      if [[ -n "${hook}" ]]; then
+        i_generate_template_hook "${config_hook}" -- "${file_path}" "${hook}"
       else
-        local file_path="${GEN_PACKAGE_DIR}/${package_name}.${PACKAGE_MANAGER}"
-      fi
+        $generate_main && prompt_boolean generate_main "Generate main package (default=${generate_main})? "
+        ! $generate_pre prompt_boolean generate_pre "Generate pre package (default=${generate_pre})? "
+        ! $generate_pre prompt_boolean generate_post "Generate post package (default=${generate_post})? "
 
+        $generate_main && i_generate_template_main "${config_hook}" -- "${file_path}"
+        $generate_pre  && i_generate_template_pre  "${config_hook}" -- "${file_path}"
+        $generate_post && i_generate_template_post "${config_hook}" -- "${file_path}"
+      fi
+    else
+      # Ensure destination directory
       if [[ ! -d "${GEN_PACKAGE_DIR}" ]]; then
         if execlog "mkdir -p '${GEN_PACKAGE_DIR}'"; then
           ok "'${GEN_PACKAGE_DIR}' directory created"
@@ -316,20 +401,20 @@ function _main() {
 
       local continue=""
       if $GENERATE_PRE || $GENERATE_POST; then
-        if ! $SKIP_MAIN && confirm "Would you like to generate the main package template? (Y/y): "; then
-          generate_template_main ${config} -- "${file_path}"
+        if $GENERATE_MAIN && confirm "Would you like to generate the main package template? (Y/y): "; then
+          generate_template_main "${config}" -- "${file_path}"
           res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
         fi
         if $GENERATE_PRE; then
-          generate_template_pre ${config} -- "${file_path}.pre"
+          generate_template_pre "${config}" -- "${file_path}.pre"
           res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
         fi
         if $GENERATE_POST; then
-          generate_template_post ${config} -- "${file_path}.post"
+          generate_template_post "${config}" -- "${file_path}.post"
           res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
         fi
       else
-        generate_template_main ${config} -- "${file_path}"
+        generate_template_main "${config}" -- "${file_path}"
         res=$?; [[ $res -ne $BASH_EX_OK ]] && return $res
       fi
     fi
@@ -340,7 +425,7 @@ function _main() {
 
 
 res=0
-_main
+_main "$@"
 res=$?
 
 unset SKIP_CONFIRM
@@ -357,9 +442,9 @@ unset PACKAGE_MANAGER
 unset PACKAGE_NAME
 unset DESTINATION
 unset GEN_PACKAGE_DIR
+unset GENERATE_MAIN
 unset GENERATE_PRE
 unset GENERATE_POST
-unset SKIP_MAIN
 unset SKIP_EDIT
 unset AS_ROOT
 unset ALLOW_DEP_FAIL
diff --git a/install/install b/install/install
--- a/install/install
+++ b/install/install
@@ -24,7 +24,8 @@ include "${EZ_INSTALL_HOME}/generate/utils/generate.sh"
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
 readonly EZ_INSTALL_VERSION="0.3 BETA"
-readonly SCRIPT_ARGS="${@}"
+readonly SCRIPT_ARGS="$@"
+readonly SCRIPT_ARGS_NUM=$#
 
 ############################################################### FLAG OPTIONS ###
 
@@ -118,40 +119,6 @@ EOF
 
 
 function handle_args() {
-  local arg=
-  for arg in ${@}; do
-    local delim=""
-    case "${arg}" in
-      # translate --gnu-long-options to -g (short options)
-      --package-dir)    args="${args:-}-D ";;
-      --generate)       args="${args:-}-c ";;
-      --skip-generate)  args="${args:-}-C ";;
-      --json)           args="${args:-}-j ";;
-      --destination)    args="${args:-}-o ";;
-      --quiet)          args="${args:-}-q ";;
-      --force)          args="${args:-}-f ";;
-      --no-force)       args="${args:-}-F ";;
-      --recurse)        args="${args:-}-r ";;
-      --no-recurse)     args="${args:-}-R ";;
-      --as-root)        args="${args:-}-s ";;
-      --no-root)        args="${args:-}-S ";;
-      --allow-dep-fail) args="${args:-}-w ";;
-      --no-dep-fail)    args="${args:-}-W ";;
-      --version)        args="${args:-}-V ";;
-      --debug)          args="${args:-}-x ";;
-      --skip-confirm)   args="${args:-}-y ";;
-      --no-colors)      args="${args:-}-z ";;
-      --help)           args="${args:-}-h ";;
-      # pass through anything else
-      *)
-        [[ "${arg:0:1}" == "-" ]] || delim="\""
-        args="${args:-}${delim}${arg}${delim} "
-        ;;
-    esac
-  done
-
-  eval set -- ${args:-}
-
   # Install configs
   [[ -z "${SKIP_CONFIRM+x}" ]]    && SKIP_CONFIRM=false
   [[ -z "${VERBOSE+x}" ]]         && VERBOSE=true
@@ -170,62 +137,111 @@ function handle_args() {
   [[ -z "${ALLOW_DEP_FAIL+x}" ]] && ALLOW_DEP_FAIL=false
   CONFIG=""
 
-  OPTIND=1
-  while getopts "D:o:cCfFjqrRsSwWxyzhV" opt; do
-    case ${opt} in
-      D)
-        LOCAL_PACKAGE_ROOT_DIR="${OPTARG}"
-        ;;
-      o)
-        DESTINATION="${OPTARG}"
-        ;;
-      c)
-        GENERATE=true
-        ;;
-      C)
-        SKIP_GENERATE=true
-        ;;
+  #== parse options ==#
+  # Ref: https://www.uxora.com/unix/shell-script/22-handle-long-options-with-getopts
+
+  # Especially useful when relaying script args with group quoted OPTARG
+  eval set -- ${@:-}
+
+  local -A long_opts_map
+  long_opts_map=(
+    ['packagedir']=D
+    ['generate']=c
+    ['skipgenerate']=C
+    ['json']=j
+    ['destination']=o
+    ['quiet']=q
+    ['force']=f
+    ['noforce']=F
+    ['recurse']=r
+    ['norecurse']=R
+    ['asroot']=s
+    ['noroot']=S
+    ['allowdepfail']=w
+    ['nodepfail']=W
+    ['version']=V
+    ['debug']=x
+    ['skipconfirm']=y
+    ['nocolors']=z
+    ['help']=h
+  )
+
+  local script_opts=':D:o:cCfFjqrRsSwWxyzhV-:'
+  local script_args="$@"
+  local script_args_num=$#
+
+  local OPTIND=1
+  while getopts ${script_opts} OPTION; do
+    #== translate long options to short ==#
+    if [[ "x$OPTION" == "x-" ]]; then
+      LONG_OPTION=$OPTARG
+      LONG_OPTARG=$(echo $LONG_OPTION | grep "=" | cut -d'=' -f2)
+      LONG_OPTIND=-1
+
+      [[ "x$LONG_OPTARG" = "x" ]] && LONG_OPTIND=$OPTIND || LONG_OPTION=$(echo $OPTARG | cut -d'=' -f1)
+      [[ $LONG_OPTIND -ne -1 ]] && eval LONG_OPTARG="\$$LONG_OPTIND"
+
+      OPTION=${long_opts_map[$LONG_OPTION]}
+      [[ "x$OPTION" = "x" ]] &&  OPTION="?" OPTARG="-$LONG_OPTION"
+
+      if [[ $( echo "${script_opts}" | grep -c "${OPTION}:" ) -eq 1 ]]; then
+        # OPTION followed by another option instead of argument will be omitted.
+        if [[ "x${LONG_OPTARG}" = "x" ]] || [[ "${LONG_OPTARG}" = -* ]]; then
+          OPTION=":" OPTARG="-$LONG_OPTION"
+        else
+          OPTARG="$LONG_OPTARG";
+          if [[ $LONG_OPTIND -ne -1 ]]; then
+            [[ $OPTIND -le $script_args_num ]] && OPTIND=$(( $OPTIND+1 ))
+            shift $OPTIND
+            OPTIND=1
+          fi
+        fi
+      fi
+    fi
+
+    # OPTION followed by another option instead of argument will be omitted.
+    if [[ "x${OPTION}" != "x:" ]] && [[ "x${OPTION}" != "x?" ]] && [[ "${OPTARG:-}" = -* ]]; then
+      OPTARG="$OPTION" OPTION=":"
+    fi
+
+    #== manage options ==#
+    case "$OPTION" in
+      D) LOCAL_PACKAGE_ROOT_DIR="${OPTARG}" ;;
+      o) DESTINATION="${OPTARG}" ;;
+      f) FORCE=true;           CONFIG="${CONFIG} -${OPTION}" ;;
+      F) FORCE=false;          CONFIG="${CONFIG} -${OPTION}" ;;
+      r) RECURSIVE=true;       CONFIG="${CONFIG} -${OPTION}" ;;
+      R) RECURSIVE=false;      CONFIG="${CONFIG} -${OPTION}" ;;
+      s) AS_ROOT=true;         CONFIG="${CONFIG} -${OPTION}" ;;
+      S) AS_ROOT=false;        CONFIG="${CONFIG} -${OPTION}" ;;
+      w) ALLOW_DEP_FAIL=true;  CONFIG="${CONFIG} -${OPTION}" ;;
+      W) ALLOW_DEP_FAIL=false; CONFIG="${CONFIG} -${OPTION}" ;;
+      c) GENERATE=true ;;
+      C) SKIP_GENERATE=true ;;
+      y) SKIP_CONFIRM=true ;;
+      q) VERBOSE=false; LOG_DEBUG_LEVEL=3 ;;
+      x) DEBUG=true; LOG_DEBUG_LEVEL=7 ;;
       j)
         JSON=true
         error "JSON data parsing is currently not supported"
         exit $BASH_EX_GENERAL
         ;;
-      q)
-        VERBOSE=false
-        LOG_DEBUG_LEVEL=3
-        ;;
-      f) FORCE=true;           CONFIG="${CONFIG} -${opt}" ;;
-      F) FORCE=false;          CONFIG="${CONFIG} -${opt}" ;;
-      r) RECURSIVE=true;       CONFIG="${CONFIG} -${opt}" ;;
-      R) RECURSIVE=false;      CONFIG="${CONFIG} -${opt}" ;;
-      s) AS_ROOT=true;         CONFIG="${CONFIG} -${opt}" ;;
-      S) AS_ROOT=false;        CONFIG="${CONFIG} -${opt}" ;;
-      w) ALLOW_DEP_FAIL=true;  CONFIG="${CONFIG} -${opt}" ;;
-      W) ALLOW_DEP_FAIL=false; CONFIG="${CONFIG} -${opt}" ;;
-      x)
-        DEBUG=true
-        LOG_DEBUG_LEVEL=7
-        ;;
-      y)
-        SKIP_CONFIRM=true
-        ;;
       z)
         ENABLE_COLORS=false
         include "${EZ_INSTALL_HOME}/common/colors.sh"
         ;;
-      h)
-        usage; exit $BASH_EX_OK
-        ;;
-      V)
-        echo "${SCRIPT_NAME} ${EZ_INSTALL_VERSION}"; exit $BASH_EX_OK
-        ;;
+      h) usage; exit $BASH_EX_OK ;;
+      V) echo "${SCRIPT_NAME} ${EZ_INSTALL_VERSION}"; exit $BASH_EX_OK ;;
+      \?) echo "An invalid option has been entered: ${OPTARG:-}" ;;
+      :) echo "The additional argument for option ${OPTARG:-} was omitted." ;;
       *)
         usage
         error "Invalid flag option(s)"
         exit $BASH_SYS_EX_USAGE
     esac
   done
-  shift "$((OPTIND-1))"
+  shift $((${OPTIND} - 1))
+
 
   if [[ -p /dev/stdin ]]; then
     usage
@@ -274,7 +290,7 @@ function _main () {
   local res=0
 
   script_vars
-  handle_args "${SCRIPT_ARGS}"
+  handle_args "$@"
   res=$?
   [[ $res -ne $BASH_EX_OK ]] && return $res
 
@@ -318,7 +334,7 @@ function _main () {
 
 
 res=0
-_main
+_main "$@"
 res=$?
 
 unset EZ_DOWNLOADS_DIR
