refactor(all): Update

diff --git a/dot/actions/dist b/dot/actions/dist
--- a/dot/actions/dist
+++ b/dot/actions/dist
@@ -1,112 +1,203 @@
 #!/bin/bash
 
+set -o pipefail
+set -o nounset
+
 ################################################################################
-# Distribute all specified dotfiles in DOTFILES_LIST from DOTFILES_REPO
-# into DOTFILES_LOCAL.
+# Distribute all specified dotfiles in DOTFILES_LIST from DOT_LOCAL_REPO_DIR
+# into DOT_LOCAL_DIR.
 # Uses `cmp` to compare files and `diff -c` to display changes when `-V` flag is
 # given.
 #
 # The $DOTFILESRC specifies the location of .dotfilesrc file to override default
 # script variables.
 #
-################################# DEPENDENCIES #################################
-#
-# ../../scripting-utils/colors  Pre-defined global variables for colorful string
-#                               outputs.
-# ../../scripting-utils/utils   Utility functions for detailed debugging
-#                               outputs.
-# ./detect                      Changes and deletion detection functions.
-#
-########################### Script Global Variables ############################
-#
-# DOTFILES_LIST  = Bash array list of config (dot) files or directory to update.
-# DOTFILES_LOCAL = Default local dotfiles directory to distribute dotfiles into.
-# DOTFILES_REPO  = Default dotfiles repo directory to distribute dotfiles from.
-# LOG_FILE_DIR   = Log file directory.
-# LOG_FILE       = Log file name. Only logs on `-d` flag or debug mode.
-#                  Defaults to current timestamp.
-#
 ################################################################################
 # Author : Mark Lucernas <https://github.com/marklcrns>
 # Date   : 2020-08-05
-################################################################################
-# Updates:
-#   2021-01-06 - Added ignore feature with DOTFILES_IGNORE_LIST string array.
-#                Ignored files will not be updated and distributed.
 #
 ################################################################################
 
 
 
 
+# Essential sources
+source "$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")/../../.ez-installrc"
+source "${EZ_INSTALL_HOME}/common/include.sh"
+
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
-# Default script variables
-DOTFILES_LIST=()
-DOTFILES_IGNORE_LIST=()
-DOTFILES_LOCAL="${HOME}"
-DOTFILES_REPO="${HOME}/.dotfiles"
-LOG_FILE_DIR="${HOME}/log"
-LOG_FILE="$(date +"%Y-%m-%dT%H:%M:%S")_$(basename -- $0).log"
-
-SCRIPTPATH="$(realpath -s $0)"
-SCRIPTDIR=$(dirname ${SCRIPTPATH})
-
-############################################## EXTERNAL DEPENDENCIES SCRIPTS ###
-
-# Ansi color code variables
-if [[ -e "${SCRIPTDIR}/../../scripting-utils/colors" ]]; then
-  source "${SCRIPTDIR}/../../scripting-utils/colors"
-else
-  echo "${SCRIPTPATH} WARNING: Failed to source '../../scripting-utils/colors' dependency"
-  echo
-fi
-# Utility functions
-if [[ -e "${SCRIPTDIR}/../../scripting-utils/utils" ]]; then
-  source "${SCRIPTDIR}/../../scripting-utils/utils"
-else
-  echo "${SCRIPTPATH} ERROR: Failed to source '../../scripting-utils/utils' dependency"
-  exit 1
-fi
-# Detect utility for changes and deletion detection
-if [[ -e "${SCRIPTDIR}/../actions/detect" ]]; then
-  source "${SCRIPTDIR}/../actions/detect"
-else
-  echo "${SCRIPTPATH} ERROR: Failed to source './../actions/detect' dependency"
-  exit 1
-fi
+readonly EZ_DOT_DIST_VERSION="0.1 BETA"
+readonly SCRIPT_ARGS=( "${@}" )
 
 # Source rc file if exist
 [[ -e "${DOTFILESRC}" ]] && source "${DOTFILESRC}"
 
+############################################## EXTERNAL DEPENDENCIES SCRIPTS ###
+
+include "${EZ_INSTALL_HOME}/common/common.sh"
+include "${EZ_INSTALL_HOME}/common/colors.sh"
+include "${EZ_INSTALL_HOME}/common/const.sh"
+include "${EZ_INSTALL_HOME}/dot/utils/detect.sh"
+include "${EZ_INSTALL_HOME}/man/print.sh"
+include "${EZ_INSTALL_HOME}/actions.sh"
+
+
+# Default script variables
+DOTFILES_LIST=()
+LOG_FILE_DIR="${HOME}/log"
+LOG_FILE="$(date +"%Y-%m-%dT%H:%M:%S")_$(basename -- $0).log"
+
 ############################################################### FLAG OPTIONS ###
 
 # Display help
-usage() {
-cat << EOF
-USAGE:
-
-Distribute all specified dotfiles in DOTFILES_LIST from DOTFILES_REPO into
-DOTFILES_LOCAL.
-
-  dotdist
-  dotdist [ -bdDqvVy ] [ -r dotfilesrc-path ]
-  dotdist [ dotfiles-repo ] [ dotfiles-local ]
-
-OPTIONS:
-
-  -b  backup files
-  -d  skip file deletion
-  -D  debug mode (redirect output in log file)
-  -q  quite output
-  -r  specify dotfilesrc path
-  -v  verbose output
-  -V  very verbose output
-  -y  skip confirmation
-  -h  help
-
-EOF
+function usage() {
+  print_page "${EZ_INSTALL_HOME}/man/ez_dot_dist_usage"
 }
+
+
+function handle_args() {
+  # Standard configs
+  [[ -z "${SKIP_CONFIRM+x}" ]]    && SKIP_CONFIRM=false
+  [[ -z "${VERBOSE+x}" ]]         && VERBOSE=true
+  [[ -z "${DEBUG+x}" ]]           && DEBUG=false
+  [[ -z "${LOG_DEBUG_LEVEL+x}" ]] && LOG_DEBUG_LEVEL=4
+  [[ -z "${ENABLE_COLORS+x}" ]]   && ENABLE_COLORS=true
+
+  # dist configs
+  [[ -z "${HAS_TMP_RC_FILE+x}" ]] && HAS_TMP_RC_FILE=false
+  [[ -z "${IS_BACKUP+x}" ]]       && IS_BACKUP=false
+  [[ -z "${NO_DELETE+x}" ]]       && NO_DELETE=false
+
+  #== parse options ==#
+  # Ref: https://www.uxora.com/unix/shell-script/22-handle-long-options-with-getopts
+
+  # Especially useful when relaying script args with group quoted OPTARG
+  eval set -- "${@:-}"
+
+  local -A long_opts_map
+  long_opts_map=(
+    ['dotfilesrc']=a
+    ['backup']=c
+    ['no-delete']=c
+    ['quiet']=q
+    ['debug']=x
+    ['skip-confirm']=y
+    ['no-colors']=z
+    ['help']=h
+    ['version']=V
+  )
+
+  local script_opts=':acqxyzhV-:'
+  local script_args_num=$#
+
+  local OPTIND=1
+  while getopts ${script_opts} OPTION; do
+    #== translate long options to short ==#
+    if [[ "x$OPTION" == "x-" ]]; then
+      LONG_OPTION=$OPTARG
+      LONG_OPTARG=$(echo "$LONG_OPTION" | grep "=" | cut -d'=' -f2)
+      LONG_OPTIND=-1
+
+      [[ "x$LONG_OPTARG" = "x" ]] && LONG_OPTIND=$OPTIND || LONG_OPTION=$(echo "$OPTARG" | cut -d'=' -f1)
+      [[ $LONG_OPTIND -ne -1 ]] && eval LONG_OPTARG="\$$LONG_OPTIND"
+
+      OPTION=${long_opts_map[$LONG_OPTION]}
+      [[ "x$OPTION" = "x" ]] &&  OPTION="?" OPTARG="-$LONG_OPTION"
+
+      if [[ $( echo "${script_opts}" | grep -c "${OPTION}:" ) -eq 1 ]]; then
+        # OPTION followed by another option instead of argument will be omitted.
+        if [[ "x${LONG_OPTARG}" = "x" ]] || [[ "${LONG_OPTARG}" = -* ]]; then
+          OPTION=":" OPTARG="-$LONG_OPTION"
+        else
+          OPTARG="$LONG_OPTARG";
+          if [[ $LONG_OPTIND -ne -1 ]]; then
+            [[ $OPTIND -le $script_args_num ]] && OPTIND=$(( OPTIND+1 ))
+            shift $OPTIND
+            OPTIND=1
+          fi
+        fi
+      fi
+    fi
+
+    # OPTION followed by another option instead of argument will be omitted.
+    if [[ "x${OPTION}" != "x:" ]] && [[ "x${OPTION}" != "x?" ]] && [[ "${OPTARG:-}" = -* ]]; then
+      OPTARG="$OPTION" OPTION=":"
+    fi
+
+    #== manage options ==#
+    case "$OPTION" in
+      a) DOT_BACKUP_AUTO_CLEAN=true ;;
+      c) CLEAN_BACKUPS=true ;;
+      y) SKIP_CONFIRM=true ;;
+      q) VERBOSE=false; LOG_DEBUG_LEVEL=3 ;;
+      x) DEBUG=true; LOG_DEBUG_LEVEL=7 ;;
+      z) ENABLE_COLORS=false
+         include "${EZ_INSTALL_HOME}/common/colors.sh"
+         ;;
+      h) usage; exit "$BASH_EX_OK" ;;
+      V) echo "${SCRIPT_NAME} ${EZ_DOT_BACKUP_VERSION}"; exit "$BASH_EX_OK" ;;
+      \?) error "${BASH_SYS_MSG_USAGE_INVARG}: ${OPTARG:-}" "$BASH_EX_GENERAL" ;;
+      :) error "The additional argument for option ${OPTARG:-} was omitted." "$BASH_EX_GENERAL" ;;
+      *) usage; error "Invalid flag option(s)" "$BASH_SYS_EX_USAGE" ;;
+    esac
+
+  done
+  shift $(( OPTIND-1 ))
+
+
+  # Disallow piped cli args
+  if [[ -p /dev/stdin ]];             then usage; error "Piped arguments not supported" "$BASH_SYS_EX_USAGE"; fi
+  # Disallow Stdin redirection
+  if [[ ! -t 0 && ! -p /dev/stdin ]]; then usage; error "Stdin redirection not supported" "$BASH_SYS_EX_USAGE"; fi
+
+
+  # Validate local dotfiles directory argument
+  if [[ -n "${1+x}" ]]; then
+    _dot_local_dir="${1}"
+    if [[ -d "${_dot_local_dir}" ]]; then
+      DOT_LOCAL_DIR="${_dot_local_dir}"
+    else
+      error "Invalid local dotfiles directory path '${DOT_LOCAL_DIR}'" 1
+    fi
+
+    # Validate dotfiles backup directory argument
+    if [[ -n "${2+x}" ]]; then
+      _dot_backup_dir="${2}"
+      if [[ -d "${_dot_backup_dir}" ]]; then
+        DOT_BACKUP_DIR="${_dot_backup_dir}"
+      else
+        error "Invalid dotfiles backup directory path '${DOT_BACKUP_DIR}'" 1
+      fi
+    else
+      error "Missing dotfiles backup directory path argument" 1
+    fi
+  fi
+
+  strip_trailing_forwardslash DOT_BACKUP_DIR
+  strip_trailing_forwardslash DOT_LOCAL_DIR
+
+  if [[ -n "${HAS_TMP_RC_FILE}" ]]; then
+    if [[ -e "${tmp_rc_file_path}" ]]; then
+      source "${tmp_rc_file_path}"
+    else
+      error "Invalid rc file path '${tmp_rc_file_path}'" 1
+    fi
+  fi
+
+  return "$BASH_EX_OK"
+}
+
+###################################################################### UTILS ###
+
+function _ctrl_c() {
+  if "${DEBUG}"; then
+    echo ""
+    log 'error' "$(basename -- "${BASH_SOURCE[1]}").${FUNCNAME[1]}(): Interrupted!" "$BASH_EX_TERMCTRLC"
+  fi
+}
+
+
 
 # Set flag options
 while getopts "bdDqr:vVyh" opt; do
@@ -115,12 +206,12 @@ while getopts "bdDqr:vVyh" opt; do
     d) [[ -n "$NO_DELETE"       ]] && unset NO_DELETE                  || NO_DELETE=true;;
     D) [[ -n "$DEBUG"           ]] && unset DEBUG                      || DEBUG=true;;
     q) [[ -n "$IS_QUITE"        ]] && unset IS_QUITE                   || IS_QUITE=true;;
-    r) [[ -n "$HAS_RC_FILE"     ]] && unset HAS_RC_FILE                || HAS_RC_FILE=true; tmp_rc_file_path="${OPTARG}";;
+    r) [[ -n "$HAS_TMP_RC_FILE"     ]] && unset HAS_TMP_RC_FILE                || HAS_TMP_RC_FILE=true; tmp_rc_file_path="${OPTARG}";;
     v) [[ -n "$IS_VERBOSE"      ]] && unset IS_VERBOSE                 || IS_VERBOSE=true;;
     V) [[ -n "$IS_VERY_VERBOSE" ]] && unset IS_VERBOSE IS_VERY_VERBOSE || IS_VERBOSE=true; IS_VERY_VERBOSE=true;;
     y) [[ -n "$SKIP_CONFIRM"    ]] && unset SKIP_CONFIRM               || SKIP_CONFIRM=true;;
     h) usage && exit 0;;
-    *) usage && echo -e "${SCRIPTPATH}:\n${RED}ERROR: Invalid flag.${NC}"
+    *) usage && echo -e "${SCRIPT_PATH}:\n${RED}ERROR: Invalid flag.${NC}"
       exit 1
   esac
 done 2>/dev/null
@@ -130,8 +221,8 @@ shift "$((OPTIND-1))" # explanation https://unix.stackexchange.com/a/214151
 ####################################################### PRE-EXECUTION SET UP ###
 
 # Strip trailing '/' in DIR path variables
-DOTFILES_LOCAL=$(echo ${DOTFILES_LOCAL} | sed 's,/*$,,')
-DOTFILES_REPO=$(echo ${DOTFILES_REPO} | sed 's,/*$,,')
+DOT_LOCAL_DIR=$(echo ${DOT_LOCAL_DIR} | sed 's,/*$,,')
+DOT_LOCAL_REPO_DIR=$(echo ${DOT_LOCAL_REPO_DIR} | sed 's,/*$,,')
 LOG_FILE_DIR=$(echo ${LOG_FILE_DIR} | sed 's,/*$,,')
 
 # Log stdout and stderr to $LOG_FILE in $LOG_FILE_DIR
@@ -143,7 +234,7 @@ if [[ -n "${DEBUG}" ]]; then
     mkdir -p "${LOG_FILE_DIR}"
   fi
   # Initialize log file
-  echo -e "${SCRIPTPATH} log outputs\n" > ${LOG_FILE_PATH}
+  echo -e "${SCRIPT_PATH} log outputs\n" > ${LOG_FILE_PATH}
 fi
 
 ################################################## SCRIPT ARGUMENTS HANDLING ###
@@ -152,28 +243,28 @@ if [[ -n $1 ]]; then
   tmp_dotfiles_repo="$1"
   # Validate dotfiles repo directory argument
   if [[ -d "${tmp_dotfiles_repo}" && -d "${tmp_dotfiles_repo}/.git" ]]; then
-    DOTFILES_REPO="${tmp_dotfiles_repo}"
+    DOT_LOCAL_REPO_DIR="${tmp_dotfiles_repo}"
     # Strip trailing '/' in DIR path variables
-    DOTFILES_REPO=$(echo ${DOTFILES_REPO} | sed 's,/*$,,')
+    DOT_LOCAL_REPO_DIR=$(echo ${DOT_LOCAL_REPO_DIR} | sed 's,/*$,,')
   else
-    error "Invalid dotfiles repository directory path '${DOTFILES_REPO}'" 1
+    error "Invalid dotfiles repository directory path '${DOT_LOCAL_REPO_DIR}'" 1
   fi
   if [[ -n $2 ]]; then
     tmp_dotfiles_local="$2"
     # Validate local dotfiles directory argument
     if [[ -d "${tmp_dotfiles_local}" ]]; then
-      DOTFILES_LOCAL="${tmp_dotfiles_local}"
+      DOT_LOCAL_DIR="${tmp_dotfiles_local}"
       # Strip trailing '/' in DIR path variables
-      DOTFILES_LOCAL=$(echo ${DOTFILES_LOCAL} | sed 's,/*$,,')
+      DOT_LOCAL_DIR=$(echo ${DOT_LOCAL_DIR} | sed 's,/*$,,')
     else
-      error "Invalid local dotfiles directory path '${DOTFILES_LOCAL}'" 1
+      error "Invalid local dotfiles directory path '${DOT_LOCAL_DIR}'" 1
     fi
   else
     error "Missing local dotfiles directory path argument" 1
   fi
 fi
 
-if [[ -n "${HAS_RC_FILE}" ]]; then
+if [[ -n "${HAS_TMP_RC_FILE}" ]]; then
   if [[ -e "${tmp_rc_file_path}" ]]; then
     source "${tmp_rc_file_path}"
   else
@@ -191,9 +282,9 @@ echolog "Detecting dotfiles changes..."
 echolog
 for dotfile in ${DOTFILES_LIST[@]}; do
   # Strip source directory from path
-  source_stripped=$(echo "${dotfile}" | sed "s,${DOTFILES_LOCAL}/,,")
+  source_stripped=$(echo "${dotfile}" | sed "s,${DOT_LOCAL_DIR}/,,")
 
-  source_file="${DOTFILES_REPO}/${source_stripped}"
+  source_file="${DOT_LOCAL_REPO_DIR}/${source_stripped}"
   target_file="${dotfile}"
 
   detect_change "${source_file}" "${target_file}" changes changes_count files_count
@@ -296,7 +387,7 @@ echolog
 # Confirmation
 if [[ -z "${SKIP_CONFIRM}" ]]; then
   log "Do you wish to continue? (Y/y): \n" 1
-  ${SCRIPTDIR}/../../scripting-utils/confirm "Do you wish to continue? (Y/y): "
+  ${SCRIPT_DIR}/../../scripting-utils/confirm "Do you wish to continue? (Y/y): "
   if [[ "${?}" -eq 1 ]]; then
     abort "Update aborted."
   elif [[ "${?}" -eq 2 ]]; then
@@ -309,11 +400,11 @@ if [[ -n "${IS_BACKUP}" ]]; then
   echolog "Backing up dotfiles..."
   echolog
   if [[ -n "${IS_VERY_VERBOSE}" ]]; then
-    ${SCRIPTDIR}/dotbackup -Vya
+    ${SCRIPT_DIR}/dotbackup -Vya
   elif [[ -n "${IS_VERBOSE}" ]]; then
-    ${SCRIPTDIR}/dotbackup -vya
+    ${SCRIPT_DIR}/dotbackup -vya
   else
-    ${SCRIPTDIR}/dotbackup -ya
+    ${SCRIPT_DIR}/dotbackup -ya
   fi
 fi
 
@@ -359,9 +450,9 @@ done
 # Final check
 for dotfile in ${DOTFILES_LIST[@]}; do
   # Strip source directory from path
-  source_stripped=$(echo "$dotfile" | sed "s,${DOTFILES_LOCAL}/,,")
+  source_stripped=$(echo "$dotfile" | sed "s,${DOT_LOCAL_DIR}/,,")
 
-  source_file="${DOTFILES_REPO}/${source_stripped}"
+  source_file="${DOT_LOCAL_REPO_DIR}/${source_stripped}"
   target_file="${dotfile}"
 
   detect_change "${source_file}" "${target_file}" changes changes_count files_count 1
diff --git a/install/install b/install/install
--- a/install/install
+++ b/install/install
@@ -26,231 +26,279 @@ include "${EZ_INSTALL_HOME}/man/print.sh"
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
 readonly EZ_INSTALL_VERSION="0.3 BETA"
-readonly SCRIPT_ARGS=( "${@}" )
+readonly SCRIPT_ARGS=("${@}")
 
 ############################################################### FLAG OPTIONS ###
 
-
 # TODO: Separate manual from usage. Also, auto generate exit codes.
 function usage() {
-  print_page "${EZ_INSTALL_HOME}/man/ez_install_usage"
+	print_page "${EZ_INSTALL_HOME}/man/ez_install_usage"
 }
 
-
 function handle_args() {
-  # Standard configs
-  [[ -z "${SKIP_CONFIRM+x}" ]]    && SKIP_CONFIRM=false
-  [[ -z "${VERBOSE+x}" ]]         && VERBOSE=true
-  [[ -z "${DEBUG+x}" ]]           && DEBUG=false
-  [[ -z "${LOG_DEBUG_LEVEL+x}" ]] && LOG_DEBUG_LEVEL=4
-  [[ -z "${ENABLE_COLORS+x}" ]]   && ENABLE_COLORS=true
+	# Standard configs
+	[[ -z "${SKIP_CONFIRM+x}" ]] && SKIP_CONFIRM=false
+	[[ -z "${VERBOSE+x}" ]] && VERBOSE=true
+	[[ -z "${DEBUG+x}" ]] && DEBUG=false
+	[[ -z "${LOG_DEBUG_LEVEL+x}" ]] && LOG_DEBUG_LEVEL=4
+	[[ -z "${ENABLE_COLORS+x}" ]] && ENABLE_COLORS=true
 
-  # Install configs
-  [[ -z "${INSTALL_SKIP_GENERATE+x}" ]] && INSTALL_SKIP_GENERATE=false
-  [[ -z "${JSON+x}" ]]                  && JSON=false
-  [[ -z "${DESTINATION+x}" ]]           && DESTINATION="${HOME}/Downloads"
+	# Install configs
+	[[ -z "${INSTALL_SKIP_GENERATE+x}" ]] && INSTALL_SKIP_GENERATE=false
+	[[ -z "${JSON+x}" ]] && JSON=false
+	[[ -z "${DESTINATION+x}" ]] && DESTINATION="${HOME}/Downloads"
 
-  # Package configs
-  [[ -z "${FORCE+x}" ]]          && FORCE=false
-  [[ -z "${RECURSIVE+x}" ]]      && RECURSIVE=true
-  [[ -z "${AS_ROOT+x}" ]]        && AS_ROOT=false
-  [[ -z "${ALLOW_DEP_FAIL+x}" ]] && ALLOW_DEP_FAIL=false
-  PACKAGE_CONFIGS=()
+	# Package configs
+	[[ -z "${FORCE+x}" ]] && FORCE=false
+	[[ -z "${RECURSIVE+x}" ]] && RECURSIVE=true
+	[[ -z "${AS_ROOT+x}" ]] && AS_ROOT=false
+	[[ -z "${ALLOW_DEP_FAIL+x}" ]] && ALLOW_DEP_FAIL=false
+	PACKAGE_CONFIGS=()
 
-  #== parse options ==#
-  # Ref: https://www.uxora.com/unix/shell-script/22-handle-long-options-with-getopts
+	#== parse options ==#
+	# Ref: https://www.uxora.com/unix/shell-script/22-handle-long-options-with-getopts
 
-  # Especially useful when relaying script args with group quoted OPTARG
-  eval set -- "${@:-}"
+	# Especially useful when relaying script args with group quoted OPTARG
+	eval set -- "${@:-}"
 
-  local -A long_opts_map
-  long_opts_map=(
-    ['package-dir']=D
-    ['json']=j
-    ['destination']=o
-    ['quiet']=q
-    ['force']=f
-    ['no-force']=F
-    ['recurse']=r
-    ['skip-generate']=G
-    ['no-recurse']=R
-    ['as-root']=s
-    ['no-root']=S
-    ['allow-dep-fail']=w
-    ['no-dep-fail']=W
-    ['version']=V
-    ['debug']=x
-    ['skip-confirm']=y
-    ['no-colors']=z
-    ['help']=h
-  )
+	local -A long_opts_map
+	long_opts_map=(
+		['package-dir']=D
+		['json']=j
+		['destination']=o
+		['quiet']=q
+		['force']=f
+		['no-force']=F
+		['recurse']=r
+		['skip-generate']=G
+		['no-recurse']=R
+		['as-root']=s
+		['no-root']=S
+		['allow-dep-fail']=w
+		['no-dep-fail']=W
+		['version']=V
+		['debug']=x
+		['skip-confirm']=y
+		['no-colors']=z
+		['help']=h
+	)
 
-  local script_opts=':D:o:fFGjqrRsSwWxyzhV-:'
-  local script_args_num=$#
+	local script_opts=':D:o:fFGjqrRsSwWxyzhV-:'
+	local script_args_num=$#
 
-  local OPTIND=1
-  while getopts ${script_opts} OPTION; do
-    #== translate long options to short ==#
-    if [[ "x$OPTION" == "x-" ]]; then
-      LONG_OPTION=$OPTARG
-      LONG_OPTARG=$(echo "$LONG_OPTION" | grep "=" | cut -d'=' -f2)
-      LONG_OPTIND=-1
+	local OPTIND=1
+	while getopts ${script_opts} OPTION; do
+		#== translate long options to short ==#
+		if [[ "x$OPTION" == "x-" ]]; then
+			LONG_OPTION=$OPTARG
+			LONG_OPTARG=$(echo "$LONG_OPTION" | grep "=" | cut -d'=' -f2)
+			LONG_OPTIND=-1
 
-      [[ "x$LONG_OPTARG" = "x" ]] && LONG_OPTIND=$OPTIND || LONG_OPTION=$(echo "$OPTARG" | cut -d'=' -f1)
-      [[ $LONG_OPTIND -ne -1 ]] && eval LONG_OPTARG="\$$LONG_OPTIND"
+			[[ "x$LONG_OPTARG" = "x" ]] && LONG_OPTIND=$OPTIND || LONG_OPTION=$(echo "$OPTARG" | cut -d'=' -f1)
+			[[ $LONG_OPTIND -ne -1 ]] && eval LONG_OPTARG="\$$LONG_OPTIND"
 
-      OPTION=${long_opts_map[$LONG_OPTION]}
-      [[ "x$OPTION" = "x" ]] &&  OPTION="?" OPTARG="-$LONG_OPTION"
+			OPTION=${long_opts_map[$LONG_OPTION]}
+			[[ "x$OPTION" = "x" ]] && OPTION="?" OPTARG="-$LONG_OPTION"
 
-      if [[ $( echo "${script_opts}" | grep -c "${OPTION}:" ) -eq 1 ]]; then
-        # OPTION followed by another option instead of argument will be omitted.
-        if [[ "x${LONG_OPTARG}" = "x" ]] || [[ "${LONG_OPTARG}" = -* ]]; then
-          OPTION=":" OPTARG="-$LONG_OPTION"
-        else
-          OPTARG="$LONG_OPTARG";
-          if [[ $LONG_OPTIND -ne -1 ]]; then
-            [[ $OPTIND -le $script_args_num ]] && OPTIND=$(( OPTIND+1 ))
-            shift $OPTIND
-            OPTIND=1
-          fi
-        fi
-      fi
-    fi
+			if [[ $(echo "${script_opts}" | grep -c "${OPTION}:") -eq 1 ]]; then
+				# OPTION followed by another option instead of argument will be omitted.
+				if [[ "x${LONG_OPTARG}" = "x" ]] || [[ "${LONG_OPTARG}" = -* ]]; then
+					OPTION=":" OPTARG="-$LONG_OPTION"
+				else
+					OPTARG="$LONG_OPTARG"
+					if [[ $LONG_OPTIND -ne -1 ]]; then
+						[[ $OPTIND -le $script_args_num ]] && OPTIND=$((OPTIND + 1))
+						shift $OPTIND
+						OPTIND=1
+					fi
+				fi
+			fi
+		fi
 
-    # OPTION followed by another option instead of argument will be omitted.
-    if [[ "x${OPTION}" != "x:" ]] && [[ "x${OPTION}" != "x?" ]] && [[ "${OPTARG:-}" = -* ]]; then
-      OPTARG="$OPTION" OPTION=":"
-    fi
+		# OPTION followed by another option instead of argument will be omitted.
+		if [[ "x${OPTION}" != "x:" ]] && [[ "x${OPTION}" != "x?" ]] && [[ "${OPTARG:-}" = -* ]]; then
+			OPTARG="$OPTION" OPTION=":"
+		fi
 
-    #== manage options ==#
-    case "$OPTION" in
-      D) LOCAL_PACKAGE_ROOT_DIR="${OPTARG}" ;;
-      o) DESTINATION="${OPTARG}" ;;
-      f) FORCE=true;           PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      F) FORCE=false;          PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      G) INSTALL_SKIP_GENERATE=true ;;
-      r) RECURSIVE=true;       PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      R) RECURSIVE=false;      PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      s) AS_ROOT=true;         PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      S) AS_ROOT=false;        PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      w) ALLOW_DEP_FAIL=true;  PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      W) ALLOW_DEP_FAIL=false; PACKAGE_CONFIGS+=("-${OPTION}") ;;
-      y) SKIP_CONFIRM=true ;;
-      q) VERBOSE=false; LOG_DEBUG_LEVEL=3 ;;
-      x) DEBUG=true; LOG_DEBUG_LEVEL=7 ;;
-      j) JSON=true
-         error "JSON data parsing is currently not supported" "$BASH_EX_GENERAL"
-         ;;
-      z) ENABLE_COLORS=false
-         include "${EZ_INSTALL_HOME}/common/colors.sh"
-         ;;
-      h) usage; exit "$BASH_EX_OK" ;;
-      V) echo "${SCRIPT_NAME} ${EZ_INSTALL_VERSION}"; exit "$BASH_EX_OK" ;;
-      \?) error "${BASH_SYS_MSG_USAGE_INVARG}: ${OPTARG:-}" "$BASH_EX_GENERAL" ;;
-      :) error "The additional argument for option ${OPTARG:-} was omitted." "$BASH_EX_GENERAL" ;;
-      *) usage; error "Invalid flag option(s)" "$BASH_SYS_EX_USAGE" ;;
-    esac
+		#== manage options ==#
+		case "$OPTION" in
+		D) LOCAL_PACKAGE_ROOT_DIR="${OPTARG}" ;;
+		o) DESTINATION="${OPTARG}" ;;
+		f)
+			FORCE=true
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		F)
+			FORCE=false
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		G) INSTALL_SKIP_GENERATE=true ;;
+		r)
+			RECURSIVE=true
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		R)
+			RECURSIVE=false
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		s)
+			AS_ROOT=true
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		S)
+			AS_ROOT=false
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		w)
+			ALLOW_DEP_FAIL=true
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		W)
+			ALLOW_DEP_FAIL=false
+			PACKAGE_CONFIGS+=("-${OPTION}")
+			;;
+		y) SKIP_CONFIRM=true ;;
+		q)
+			VERBOSE=false
+			LOG_DEBUG_LEVEL=3
+			;;
+		x)
+			DEBUG=true
+			LOG_DEBUG_LEVEL=7
+			;;
+		j)
+			JSON=true
+			error "JSON data parsing is currently not supported" "$BASH_EX_GENERAL"
+			;;
+		z)
+			ENABLE_COLORS=false
+			include "${EZ_INSTALL_HOME}/common/colors.sh"
+			;;
+		h)
+			usage
+			exit "$BASH_EX_OK"
+			;;
+		V)
+			echo "${SCRIPT_NAME} ${EZ_INSTALL_VERSION}"
+			exit "$BASH_EX_OK"
+			;;
+		\?) error "${BASH_SYS_MSG_USAGE_INVARG}: ${OPTARG:-}" "$BASH_EX_GENERAL" ;;
+		:) error "The additional argument for option ${OPTARG:-} was omitted." "$BASH_EX_GENERAL" ;;
+		*)
+			usage
+			error "Invalid flag option(s)" "$BASH_SYS_EX_USAGE"
+			;;
+		esac
 
-  done
-  shift $(( OPTIND-1 ))
+	done
+	shift $((OPTIND - 1))
 
+	# Disallow piped cli args
+	if [[ -p /dev/stdin ]]; then
+		usage
+		error "Piped arguments not supported" "$BASH_SYS_EX_USAGE"
+	fi
+	# Disallow Stdin redirection
+	if [[ ! -t 0 && ! -p /dev/stdin ]]; then
+		usage
+		error "Stdin redirection not supported" "$BASH_SYS_EX_USAGE"
+	fi
 
-  # Disallow piped cli args
-  if [[ -p /dev/stdin ]];             then usage; error "Piped arguments not supported" "$BASH_SYS_EX_USAGE"; fi
-  # Disallow Stdin redirection
-  if [[ ! -t 0 && ! -p /dev/stdin ]]; then usage; error "Stdin redirection not supported" "$BASH_SYS_EX_USAGE"; fi
+	# Fetch cli args into $PACKAGES
+	if [[ -t 0 ]]; then
+		if [[ -n "${*+x}" ]]; then
+			IFS=" " read -r -a PACKAGES <<<"${@}"
+			readonly PACKAGES
+		else
+			usage
+			error "No package(s) provided" "$BASH_SYS_EX_USAGE"
+		fi
+	fi
 
-  # Fetch cli args into $PACKAGES
-  if [[ -t 0 ]]; then
-    if [[ -n "${*+x}" ]]; then
-      IFS=" " read -r -a PACKAGES <<< "${@}"
-      readonly PACKAGES
-    else
-      usage; error "No package(s) provided" "$BASH_SYS_EX_USAGE"
-    fi
-  fi
+	local res=0
 
-  local res=0
+	# Make sure $DESTINATION directory exist
+	if [[ ! -d "${DESTINATION}" ]]; then
+		if execlog "mkdir -p '${DESTINATION}'"; then
+			ok "'${DESTINATION}' directory created"
+		else
+			res=$?
+			error "'${DESTINATION}' creation failed" "$BASH_SYS_EX_CANTCREAT"
+		fi
+	fi
 
-  # Make sure $DESTINATION directory exist
-  if [[ ! -d "${DESTINATION}" ]]; then
-    if execlog "mkdir -p '${DESTINATION}'"; then
-      ok "'${DESTINATION}' directory created"
-    else
-      res=$?
-      error "'${DESTINATION}' creation failed" "$BASH_SYS_EX_CANTCREAT"
-    fi
-  fi
+	# Use appropriate package directory based on machine distro
+	resolve_package_dir
 
-  # Use appropriate package directory based on machine distro
-  resolve_package_dir
-
-  return "$BASH_EX_OK"
+	return "$BASH_EX_OK"
 }
 
 ###################################################################### UTILS ###
 
 function _ctrl_c() {
-  if "${DEBUG}"; then
-    echo ""
-    log 'error' "$(basename -- "${BASH_SOURCE[1]}").${FUNCNAME[1]}(): Interrupted!" "$BASH_EX_TERMCTRLC"
-  fi
+	if "${DEBUG}"; then
+		echo ""
+		log 'error' "$(basename -- "${BASH_SOURCE[1]}").${FUNCNAME[1]}(): Interrupted!" "$BASH_EX_TERMCTRLC"
+	fi
 }
 
 ############################################################# MAIN EXECUTION ###
 
-function _main () {
-  # Set up trap
-  trap _ctrl_c INT TERM
+function _main() {
+	# Set up trap
+	trap _ctrl_c INT TERM
 
-  local res=0
+	local res=0
 
-  script_vars
-  handle_args "$@"
-  res=$?
-  [[ $res -ne $BASH_EX_OK ]] && return $res
+	script_vars
+	handle_args "$@"
+	res=$?
+	[[ $res -ne $BASH_EX_OK ]] && return $res
 
-  # Sort packages from cli args
-  local -a packages=( "${PACKAGES[@]}" )
-  array_unique packages
+	# Sort packages from cli args
+	local -a packages=("${PACKAGES[@]}")
+	array_unique packages
 
-  ! ${DEBUG} && echo -e "About to install the following packages:\n"
+	! ${DEBUG} && echo -e "About to install the following packages:\n"
 
-  # Validate and configure packages
-  # TODO: Fully support json configs
-  if ! $JSON; then
-    # Do NOT double quote $CONFIG. Need word splitting, else will take as one argument
-    validate_packages "${PACKAGE_CONFIGS[@]}" -- "${packages[@]}"
-    res=$?; [[ ${res} -ne $BASH_EX_OK ]] && return $res
+	# Validate and configure packages
+	# TODO: Fully support json configs
+	if ! $JSON; then
+		# Do NOT double quote $CONFIG. Need word splitting, else will take as one argument
+		validate_packages "${PACKAGE_CONFIGS[@]}" -- "${packages[@]}"
+		res=$?
+		[[ ${res} -ne $BASH_EX_OK ]] && return $res
 
-    $DEBUG && $VERBOSE && echo "Jsonifying..."
-    # Do NOT double quote $CONFIG. Need word splitting, else will take as one argument
-    pac_array_jsonify "${PACKAGE_CONFIGS[@]}" -- packages
-  fi
+		$DEBUG && $VERBOSE && echo "Jsonifying..."
+		# Do NOT double quote $CONFIG. Need word splitting, else will take as one argument
+		pac_array_jsonify "${PACKAGE_CONFIGS[@]}" -- packages
+	fi
 
-  if $DEBUG && $VERBOSE || $JSON; then
-    for package in "${packages[@]}"; do
-      echo "${package}" | ${EZ_DEP_JQ} -r ".package"
-    done
-  fi
+	if $DEBUG && $VERBOSE || $JSON; then
+		for package in "${packages[@]}"; do
+			echo "${package}" | ${EZ_DEP_JQ} -r ".package"
+		done
+	fi
 
-  confirm "\nYou are about to install the package(s) above. Continue? (Y/y): " \
-    || exit "$BASH_EX_GENERAL"
+	confirm "\nYou are about to install the package(s) above. Continue? (Y/y): " ||
+		exit "$BASH_EX_GENERAL"
 
-  warning "Installation in progress... Do not interrupt!"
+	warning "Installation in progress... Do not interrupt!"
 
-  # Install packages
-  pac_batch_json_install "${packages[@]}"
-  res=$?; [[ $res -ne $BASH_EX_OK ]] && exit $res
+	# Install packages
+	pac_batch_json_install "${packages[@]}"
+	res=$?
+	[[ $res -ne $BASH_EX_OK ]] && exit $res
 
-  [[ -n "${packages+x}" ]] && pac_report
+	[[ -n "${packages+x}" ]] && pac_report
 
-
-  finish "Finished!"
-  return "$BASH_EX_OK"
+	finish "Finished!"
+	return "$BASH_EX_OK"
 }
 
-res=0; _main "${SCRIPT_ARGS[@]}"; res=$?
+res=0
+_main "${SCRIPT_ARGS[@]}"
+res=$?
 
 unset EZ_DOWNLOADS_DIR
 unset SKIP_CONFIRM
