style(all): Auto format with shfmt

diff --git a/dot/actions/update b/dot/actions/update
--- a/dot/actions/update
+++ b/dot/actions/update
@@ -36,10 +36,6 @@
 #
 ################################################################################
 
-
-
-
-
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
 # Default script variables
@@ -57,24 +53,24 @@ SCRIPTDIR=$(dirname ${SCRIPTPATH})
 
 # Ansi color code variables
 if [[ -e "${SCRIPTDIR}/../../scripting-utils/colors" ]]; then
-  source "${SCRIPTDIR}/../../scripting-utils/colors"
+	source "${SCRIPTDIR}/../../scripting-utils/colors"
 else
-  echo "${SCRIPTPATH} WARNING: Failed to source '../../scripting-utils/colors' dependency"
-  echo
+	echo "${SCRIPTPATH} WARNING: Failed to source '../../scripting-utils/colors' dependency"
+	echo
 fi
 # Utility functions
 if [[ -e "${SCRIPTDIR}/../../scripting-utils/utils" ]]; then
-  source "${SCRIPTDIR}/../../scripting-utils/utils"
+	source "${SCRIPTDIR}/../../scripting-utils/utils"
 else
-  echo "${SCRIPTPATH} ERROR: Failed to source '../../scripting-utils/utils' dependency"
-  exit 1
+	echo "${SCRIPTPATH} ERROR: Failed to source '../../scripting-utils/utils' dependency"
+	exit 1
 fi
 # Detect utility for changes and deletion detection
 if [[ -e "${SCRIPTDIR}/../actions/detect" ]]; then
-  source "${SCRIPTDIR}/../actions/detect"
+	source "${SCRIPTDIR}/../actions/detect"
 else
-  echo "${SCRIPTPATH} ERROR: Failed to source './../actions/detect' dependency"
-  exit 1
+	echo "${SCRIPTPATH} ERROR: Failed to source './../actions/detect' dependency"
+	exit 1
 fi
 
 # Source rc file if exist
@@ -84,7 +80,7 @@ fi
 
 # Display help
 usage() {
-cat << EOF
+	cat <<EOF
 USAGE:
 
 Updates all specified dotfiles in DOTFILES_LIST from DOTFILES_LOCAL into
@@ -111,21 +107,29 @@ EOF
 
 # Set flag options
 while getopts "bdDqvVyh" opt; do
-  case "$opt" in
-    b) [[ -n "$IS_BACKUP"       ]] && unset IS_BACKUP                  || IS_BACKUP=true;;
-    d) [[ -n "$NO_DELETE"       ]] && unset NO_DELETE                  || NO_DELETE=true;;
-    D) [[ -n "$DEBUG"           ]] && unset DEBUG                      || DEBUG=true;;
-    q) [[ -n "$IS_QUITE"        ]] && unset IS_QUITE                   || IS_QUITE=true;;
-    r) [[ -n "$HAS_RC_FILE"     ]] && unset HAS_RC_FILE                || HAS_RC_FILE=true; tmp_rc_file_path="${OPTARG}";;
-    v) [[ -n "$IS_VERBOSE"      ]] && unset IS_VERBOSE                 || IS_VERBOSE=true;;
-    V) [[ -n "$IS_VERY_VERBOSE" ]] && unset IS_VERBOSE IS_VERY_VERBOSE || IS_VERBOSE=true; IS_VERY_VERBOSE=true;;
-    y) [[ -n "$SKIP_CONFIRM"    ]] && unset SKIP_CONFIRM               || SKIP_CONFIRM=true;;
-    h) usage && exit 0;;
-    *) usage && echo -e "${SCRIPTPATH}:\n${RED}ERROR: Invalid flag.${NC}"
-      exit 1
-  esac
+	case "$opt" in
+	b) [[ -n "$IS_BACKUP" ]] && unset IS_BACKUP || IS_BACKUP=true ;;
+	d) [[ -n "$NO_DELETE" ]] && unset NO_DELETE || NO_DELETE=true ;;
+	D) [[ -n "$DEBUG" ]] && unset DEBUG || DEBUG=true ;;
+	q) [[ -n "$IS_QUITE" ]] && unset IS_QUITE || IS_QUITE=true ;;
+	r)
+		[[ -n "$HAS_RC_FILE" ]] && unset HAS_RC_FILE || HAS_RC_FILE=true
+		tmp_rc_file_path="${OPTARG}"
+		;;
+	v) [[ -n "$IS_VERBOSE" ]] && unset IS_VERBOSE || IS_VERBOSE=true ;;
+	V)
+		[[ -n "$IS_VERY_VERBOSE" ]] && unset IS_VERBOSE IS_VERY_VERBOSE || IS_VERBOSE=true
+		IS_VERY_VERBOSE=true
+		;;
+	y) [[ -n "$SKIP_CONFIRM" ]] && unset SKIP_CONFIRM || SKIP_CONFIRM=true ;;
+	h) usage && exit 0 ;;
+	*)
+		usage && echo -e "${SCRIPTPATH}:\n${RED}ERROR: Invalid flag.${NC}"
+		exit 1
+		;;
+	esac
 done 2>/dev/null
-shift "$((OPTIND-1))" # explanation https://unix.stackexchange.com/a/214151
+shift "$((OPTIND - 1))" # explanation https://unix.stackexchange.com/a/214151
 
 ####################################################### PRE-EXECUTION SET UP ###
 
@@ -136,49 +140,49 @@ LOG_FILE_DIR=$(echo ${LOG_FILE_DIR} | sed 's,/*$,,')
 
 # Log stdout and stderr to $LOG_FILE in $LOG_FILE_DIR
 if [[ -n "${DEBUG}" ]]; then
-  # Append LOG_FILE
-  LOG_FILE_PATH="${LOG_FILE_DIR}/${LOG_FILE}"
-  # Create log directory if not existing
-  if [[ ! -d "${LOG_FILE_DIR}" ]]; then
-    mkdir -p "${LOG_FILE_DIR}"
-  fi
-  # Initialize log file
-  echo -e "${SCRIPTPATH} log outputs\n" > ${LOG_FILE_PATH}
+	# Append LOG_FILE
+	LOG_FILE_PATH="${LOG_FILE_DIR}/${LOG_FILE}"
+	# Create log directory if not existing
+	if [[ ! -d "${LOG_FILE_DIR}" ]]; then
+		mkdir -p "${LOG_FILE_DIR}"
+	fi
+	# Initialize log file
+	echo -e "${SCRIPTPATH} log outputs\n" >${LOG_FILE_PATH}
 fi
 
 ################################################## SCRIPT ARGUMENTS HANDLING ###
 
 if [[ -n $1 ]]; then
-  tmp_dotfiles_local="$1"
-  # Validate local dotfiles directory argument
-  if [[ -d "${tmp_dotfiles_local}" ]]; then
-    DOTFILES_LOCAL="${tmp_dotfiles_local}"
-    # Strip trailing '/' in DIR path variables
-    DOTFILES_LOCAL=$(echo ${DOTFILES_LOCAL} | sed 's,/*$,,')
-  else
-    error "Invalid local dotfiles directory path '${DOTFILES_LOCAL}'" 1
-  fi
-  if [[ -n $2 ]]; then
-    tmp_dotfiles_repo="$2"
-    # Validate dotfiles repo directory argument
-    if [[ -d "${tmp_dotfiles_repo}" && -d "${tmp_dotfiles_repo}/.git" ]]; then
-      DOTFILES_REPO="${tmp_dotfiles_repo}"
-      # Strip trailing '/' in DIR path variables
-      DOTFILES_REPO=$(echo ${DOTFILES_REPO} | sed 's,/*$,,')
-    else
-      error "Invalid dotfiles repository directory path '${DOTFILES_REPO}'" 1
-    fi
-  else
-    error "Missing dotfiles repo directory path argument" 1
-  fi
+	tmp_dotfiles_local="$1"
+	# Validate local dotfiles directory argument
+	if [[ -d "${tmp_dotfiles_local}" ]]; then
+		DOTFILES_LOCAL="${tmp_dotfiles_local}"
+		# Strip trailing '/' in DIR path variables
+		DOTFILES_LOCAL=$(echo ${DOTFILES_LOCAL} | sed 's,/*$,,')
+	else
+		error "Invalid local dotfiles directory path '${DOTFILES_LOCAL}'" 1
+	fi
+	if [[ -n $2 ]]; then
+		tmp_dotfiles_repo="$2"
+		# Validate dotfiles repo directory argument
+		if [[ -d "${tmp_dotfiles_repo}" && -d "${tmp_dotfiles_repo}/.git" ]]; then
+			DOTFILES_REPO="${tmp_dotfiles_repo}"
+			# Strip trailing '/' in DIR path variables
+			DOTFILES_REPO=$(echo ${DOTFILES_REPO} | sed 's,/*$,,')
+		else
+			error "Invalid dotfiles repository directory path '${DOTFILES_REPO}'" 1
+		fi
+	else
+		error "Missing dotfiles repo directory path argument" 1
+	fi
 fi
 
 if [[ -n "${HAS_RC_FILE}" ]]; then
-  if [[ -e "${tmp_rc_file_path}" ]]; then
-    source "${tmp_rc_file_path}"
-  else
-    error "Invalid rc file path '${tmp_rc_file_path}'" 1
-  fi
+	if [[ -e "${tmp_rc_file_path}" ]]; then
+		source "${tmp_rc_file_path}"
+	else
+		error "Invalid rc file path '${tmp_rc_file_path}'" 1
+	fi
 fi
 
 ########################################################## SCRIPT EXECUTIONS ###
@@ -194,48 +198,48 @@ total_files_count=0
 echolog "Detecting dotfiles changes..."
 echolog
 for dotfile in ${DOTFILES_LIST[@]}; do
-  # Strip source directory from path
-  source_stripped=$(echo "$dotfile" | sed "s,${DOTFILES_LOCAL}/,,")
+	# Strip source directory from path
+	source_stripped=$(echo "$dotfile" | sed "s,${DOTFILES_LOCAL}/,,")
 
-  source_file="${dotfile}"
-  target_file="${DOTFILES_REPO}/${source_stripped}"
+	source_file="${dotfile}"
+	target_file="${DOTFILES_REPO}/${source_stripped}"
 
-  detect_change "${source_file}" "${target_file}" changes changes_count files_count
-  detect_delete "${target_file}" "${source_file}" delete delete_count
+	detect_change "${source_file}" "${target_file}" changes changes_count files_count
+	detect_delete "${target_file}" "${source_file}" delete delete_count
 
-  # Initialize counters if none
-  [[ -z "${changes_count}" ]] && changes_count=0
-  [[ -z "${delete_count}" ]] && delete_count=0
-  [[ -z "${files_count}" ]] && files_count=0
+	# Initialize counters if none
+	[[ -z "${changes_count}" ]] && changes_count=0
+	[[ -z "${delete_count}" ]] && delete_count=0
+	[[ -z "${files_count}" ]] && files_count=0
 
-  # Update changes list
-  if [[ -n "${changes}" ]]; then
-    if [[ -z ${changes_list} ]]; then
-      changes_list="${changes}"
-    else
-      changes_list="${changes_list}\n${changes}"
-    fi
-    # Increment changes counter
-    total_changes_count=$(expr ${total_changes_count} + ${changes_count})
-  fi
-  if [[ -n "${delete}" ]]; then
-    if [[ -z ${changes_list} ]]; then
-      changes_list="${delete}"
-    else
-      changes_list="${changes_list}\n${delete}"
-    fi
-    # Increment delete counter
-    if [[ -z "${NO_DELETE}" ]]; then
-      total_deleted_count=$(expr ${total_deleted_count} + ${delete_count})
-    fi
-  fi
-  # Increment total files counters
-  total_files_count=$(expr ${total_files_count} + ${files_count} + ${delete_count})
+	# Update changes list
+	if [[ -n "${changes}" ]]; then
+		if [[ -z ${changes_list} ]]; then
+			changes_list="${changes}"
+		else
+			changes_list="${changes_list}\n${changes}"
+		fi
+		# Increment changes counter
+		total_changes_count=$(expr ${total_changes_count} + ${changes_count})
+	fi
+	if [[ -n "${delete}" ]]; then
+		if [[ -z ${changes_list} ]]; then
+			changes_list="${delete}"
+		else
+			changes_list="${changes_list}\n${delete}"
+		fi
+		# Increment delete counter
+		if [[ -z "${NO_DELETE}" ]]; then
+			total_deleted_count=$(expr ${total_deleted_count} + ${delete_count})
+		fi
+	fi
+	# Increment total files counters
+	total_files_count=$(expr ${total_files_count} + ${files_count} + ${delete_count})
 done
 
 # Abort if no changes or delete detected
 [[ ${total_changes_count} -eq 0 ]] && [[ ${total_deleted_count} -eq 0 ]] &&
-  abort "\nAborting... No dotfiles to update."
+	abort "\nAborting... No dotfiles to update."
 
 echolog
 echolog "${ULINE}Files with changes:${NC}"
@@ -246,68 +250,68 @@ new_files_count=0
 
 # Loop over changes list and diff if IS_VERY_VERBOSE, else echolog source file
 while IFS= read -r file_tuple; do
-  # Split file_tuple
-  IFS=';' read -r -a file_arr <<< "${file_tuple}"
-  source_file="${file_arr[0]}"; target_file="${file_arr[1]}"
-    # Copy source to target file
-  if [[ -z "${target_file}" ]]; then # check if target_file is missing
-    if [[ -z "${NO_DELETE}" ]]; then
-      echolog "${RED}-${source_file}${NC}"
-    else
-      echolog "${RED}-${source_file} ${YELLOW}SKIPPED${NC}"
-    fi
-  elif [[ -e "${target_file}" ]]; then # check if target_file not existing
-    # Diff source and target file
-    if [[ -n "${IS_VERY_VERBOSE}" ]] && [[ -z "${IS_QUITE}" ]]; then
-      if command -v colordiff &> /dev/null; then
-        diff -c "${target_file}" "${source_file}" | colordiff
-        log "${source_file}" 1
-      else
-        diff -c "${target_file}" "${source_file}" --color
-        log "${source_file}" 1
-      fi
-    else
-      # echolog source file if not very verbose
-      echolog "${YELLOW}${source_file}${NC}"
-    fi
-    modified_files_count=$((modified_files_count+1))
-  else
-    echolog "${GREEN}+${target_file}${NC}"
-    new_files_count=$((new_files_count+1))
-  fi
+	# Split file_tuple
+	IFS=';' read -r -a file_arr <<<"${file_tuple}"
+	source_file="${file_arr[0]}"
+	target_file="${file_arr[1]}"
+	# Copy source to target file
+	if [[ -z "${target_file}" ]]; then # check if target_file is missing
+		if [[ -z "${NO_DELETE}" ]]; then
+			echolog "${RED}-${source_file}${NC}"
+		else
+			echolog "${RED}-${source_file} ${YELLOW}SKIPPED${NC}"
+		fi
+	elif [[ -e "${target_file}" ]]; then # check if target_file not existing
+		# Diff source and target file
+		if [[ -n "${IS_VERY_VERBOSE}" ]] && [[ -z "${IS_QUITE}" ]]; then
+			if command -v colordiff &>/dev/null; then
+				diff -c "${target_file}" "${source_file}" | colordiff
+				log "${source_file}" 1
+			else
+				diff -c "${target_file}" "${source_file}" --color
+				log "${source_file}" 1
+			fi
+		else
+			# echolog source file if not very verbose
+			echolog "${YELLOW}${source_file}${NC}"
+		fi
+		modified_files_count=$((modified_files_count + 1))
+	else
+		echolog "${GREEN}+${target_file}${NC}"
+		new_files_count=$((new_files_count + 1))
+	fi
 done < <(echo -e "${changes_list}") # Process substitution for outside variables
 
 # Changes and deletes tally
 echolog
 echolog "Total files to update: \t\t${total_files_count}"
 if [[ ${modified_files_count} -gt 0 ]]; then
-  echolog "${YELLOW}Total changed files: \t\t${modified_files_count}${NC}"
+	echolog "${YELLOW}Total changed files: \t\t${modified_files_count}${NC}"
 fi
 if [[ ${new_files_count} -gt 0 ]]; then
-  echolog "${GREEN}Total new files: \t\t${new_files_count}${NC}"
+	echolog "${GREEN}Total new files: \t\t${new_files_count}${NC}"
 fi
 if [[ -z ${NO_DELETE} ]]; then
-  if [[ ${total_deleted_count} -gt 0 ]]; then
-    echolog "${RED}Total delete files: \t\t${total_deleted_count}${NC}"
-  fi
+	if [[ ${total_deleted_count} -gt 0 ]]; then
+		echolog "${RED}Total delete files: \t\t${total_deleted_count}${NC}"
+	fi
 else
-  if [[ ${total_deleted_count} -gt 0 ]]; then
-    echolog "${RED}Total delete files: \t\t${YELLOW}SKIPPED${NC}"
-  fi
+	if [[ ${total_deleted_count} -gt 0 ]]; then
+		echolog "${RED}Total delete files: \t\t${YELLOW}SKIPPED${NC}"
+	fi
 fi
 echolog
 
 # Confirmation
 if [[ -z "${SKIP_CONFIRM}" ]]; then
-  log "Do you wish to continue? (Y/y): \n" 1
-  ${SCRIPTDIR}/../../scripting-utils/confirm "Do you wish to continue? (Y/y): "
-  if [[ "${?}" -eq 1 ]]; then
-    abort "Update aborted."
-  elif [[ "${?}" -eq 2 ]]; then
-    error "Unsupported shell"
-  fi
+	log "Do you wish to continue? (Y/y): \n" 1
+	${SCRIPTDIR}/../../scripting-utils/confirm "Do you wish to continue? (Y/y): "
+	if [[ "${?}" -eq 1 ]]; then
+		abort "Update aborted."
+	elif [[ "${?}" -eq 2 ]]; then
+		error "Unsupported shell"
+	fi
 fi
-
 
 # TODO: Implement more elegant dotfiles backup
 # if [[ -n "${IS_BACKUP}" ]]; then
@@ -318,33 +322,34 @@ echolog "Updating dotfiles..."
 echolog
 # Copy changes to target directory and delete missing files
 echo -e "${changes_list}" | while IFS= read -r file_tuple; do
-  IFS=';' read -r -a file_arr <<< "$file_tuple"
-  source_file="${file_arr[0]}"; target_file="${file_arr[1]}"
-  target_dir="$(dirname "${target_file}")"
-  if [[ -z "${target_file}" ]]; then # check if target_file is missing
-    if [[ -z "${NO_DELETE}" ]]; then
-      if execlog "rm -f '${source_file}'" 1; then
-        ok "${source_file} deleted"
-      else
-        error "Failed to delete ${source_file}"
-      fi
-    else
-      warning "${source_file} SKIPPING deletion"
-    fi
-  elif [[ -d "${target_dir}" ]]; then # Check target dir path
-    if execlog "cp -rL '${source_file}' '${target_file}'" 1; then
-      ok "${source_file} -> ${target_file}"
-    else
-      error "Failed to copy ${source_file} -> ${target_file}"
-    fi
-  else # Create target dir if not existing
-    execlog "mkdir -p '${target_dir}'"
-    if execlog "cp -rL '${source_file}' '${target_file}'" 1; then
-      ok "${source_file} -> ${target_file}"
-    else
-      error "Failed to copy ${source_file} -> ${target_file}"
-    fi
-  fi
+	IFS=';' read -r -a file_arr <<<"$file_tuple"
+	source_file="${file_arr[0]}"
+	target_file="${file_arr[1]}"
+	target_dir="$(dirname "${target_file}")"
+	if [[ -z "${target_file}" ]]; then # check if target_file is missing
+		if [[ -z "${NO_DELETE}" ]]; then
+			if execlog "rm -f '${source_file}'" 1; then
+				ok "${source_file} deleted"
+			else
+				error "Failed to delete ${source_file}"
+			fi
+		else
+			warning "${source_file} SKIPPING deletion"
+		fi
+	elif [[ -d "${target_dir}" ]]; then # Check target dir path
+		if execlog "cp -rL '${source_file}' '${target_file}'" 1; then
+			ok "${source_file} -> ${target_file}"
+		else
+			error "Failed to copy ${source_file} -> ${target_file}"
+		fi
+	else # Create target dir if not existing
+		execlog "mkdir -p '${target_dir}'"
+		if execlog "cp -rL '${source_file}' '${target_file}'" 1; then
+			ok "${source_file} -> ${target_file}"
+		else
+			error "Failed to copy ${source_file} -> ${target_file}"
+		fi
+	fi
 done
 
 #################################################################### WRAP UP ###
@@ -354,28 +359,27 @@ log " " 1
 log "Final check..." 1
 log " " 1
 for dotfile in ${DOTFILES_LIST[@]}; do
-  # Strip source directory from path
-  source_stripped=$(echo "$dotfile" | sed "s,${DOTFILES_LOCAL}/,,")
+	# Strip source directory from path
+	source_stripped=$(echo "$dotfile" | sed "s,${DOTFILES_LOCAL}/,,")
 
-  source_file="${dotfile}"
-  target_file="${DOTFILES_REPO}/${source_stripped}"
+	source_file="${dotfile}"
+	target_file="${DOTFILES_REPO}/${source_stripped}"
 
-  detect_change "${source_file}" "${target_file}" changes changes_count files_count 1
-  if [[ -z "${NO_DELETE}" ]]; then
-    detect_delete "${target_file}" "${source_file}" delete delete_count files_count 1
-  fi
+	detect_change "${source_file}" "${target_file}" changes changes_count files_count 1
+	if [[ -z "${NO_DELETE}" ]]; then
+		detect_delete "${target_file}" "${source_file}" delete delete_count files_count 1
+	fi
 done
 
 # Catch final check errors
 [[ ${changes_count} -gt 0 ]] || [[ ${delete_count} -gt 0 ]] &&
-  error "Dotupdate failed. Changes persists" 2
+	error "Dotupdate failed. Changes persists" 2
 
 # Clean log files
 if [[ -n "${IS_VERY_VERBOSE}" ]]; then
-  [[ -n "${DEBUG}" ]] && cleanlog 1000
+	[[ -n "${DEBUG}" ]] && cleanlog 1000
 else
-  [[ -n "${DEBUG}" ]] && cleanlog 1000 1
+	[[ -n "${DEBUG}" ]] && cleanlog 1000 1
 fi
 
 finish "Dotfiles update successful!"
-
diff --git a/dot/dot b/dot/dot
--- a/dot/dot
+++ b/dot/dot
@@ -23,59 +23,73 @@ readonly SCRIPT_ARGS_NUM=$#
 
 # TODO: Separate manual from usage. Also, auto generate exit codes.
 function usage() {
-  print_page "${EZ_INSTALL_HOME}/man/ez_dot_usage"
+	print_page "${EZ_INSTALL_HOME}/man/ez_dot_usage"
 }
 
-
 function handle_args() {
-  # Disallow piped cli args
-  if [[ -p /dev/stdin ]];             then usage; error "Piped arguments not supported" "$BASH_SYS_EX_USAGE"; fi
-  # Disallow Stdin redirection
-  if [[ ! -t 0 && ! -p /dev/stdin ]]; then usage; error "Stdin redirection not supported" "$BASH_SYS_EX_USAGE"; fi
-  # Require arguments
-  if [[ -z "${1+x}" ]];               then usage; error "${BASH_SYS_MSG_USAGE_MISSARG}" "$BASH_SYS_EX_USAGE"; fi
+	# Disallow piped cli args
+	if [[ -p /dev/stdin ]]; then
+		usage
+		error "Piped arguments not supported" "$BASH_SYS_EX_USAGE"
+	fi
+	# Disallow Stdin redirection
+	if [[ ! -t 0 && ! -p /dev/stdin ]]; then
+		usage
+		error "Stdin redirection not supported" "$BASH_SYS_EX_USAGE"
+	fi
+	# Require arguments
+	if [[ -z "${1+x}" ]]; then
+		usage
+		error "${BASH_SYS_MSG_USAGE_MISSARG}" "$BASH_SYS_EX_USAGE"
+	fi
 
-  # Especially useful when relaying script args with group quoted OPTARG
-  eval set -- "${@:-}"
+	# Especially useful when relaying script args with group quoted OPTARG
+	eval set -- "${@:-}"
 
-  local command="${1}"
-  strip_extra_whitespace command
-  shift 1
+	local command="${1}"
+	strip_extra_whitespace command
+	shift 1
 
-  # Transform args to string to quote OPTARG with whitespace.
-  # Receiving end needs to use `eval set -- ${@:-}`
-  # Ref: https://stackoverflow.com/a/1669493
-  local command_args=""
-  for i in "$@"; do
-    if [[ $i =~ ^--.*= ]]; then
-      i="$(sed -e "s/\(--.*=\)\(.*\)/\1'\2'/" <<< "$i")"
-    elif [[ $i =~ [[:space:]] ]]; then
-      i="'$i'"
-    fi
-    command_args="${command_args} $i"
-  done
+	# Transform args to string to quote OPTARG with whitespace.
+	# Receiving end needs to use `eval set -- ${@:-}`
+	# Ref: https://stackoverflow.com/a/1669493
+	local command_args=""
+	for i in "$@"; do
+		if [[ $i =~ ^--.*= ]]; then
+			i="$(sed -e "s/\(--.*=\)\(.*\)/\1'\2'/" <<<"$i")"
+		elif [[ $i =~ [[:space:]] ]]; then
+			i="'$i'"
+		fi
+		command_args="${command_args} $i"
+	done
 
-  case "${command}" in
-    bak)          ${EZ_COMMAND_DOT_BACKUP}        "${command_args}" ;;
-    clbak)        ${EZ_COMMAND_DOT_CLEAR_BACKUP}  "${command_args}" ;;
-    dist)         ${EZ_COMMAND_DOT_DISTRIBUTE}    "${command_args}" ;;
-    update)       ${EZ_COMMAND_DOT_UPDATE}        "${command_args}" ;;
-    -h|--help)    usage; exit $BASH_EX_OK ;;
-    -V|--version) echo "${SCRIPT_NAME} ${EZ_DOT_VERSION}"; exit $BASH_EX_OK ;;
-    *)
-      usage
-      error "Command '${command}' not found" $BASH_EZ_EX_COMMAND_NOTFOUND
-  esac
+	case "${command}" in
+	bak) ${EZ_COMMAND_DOT_BACKUP} "${command_args}" ;;
+	clbak) ${EZ_COMMAND_DOT_CLEAR_BACKUP} "${command_args}" ;;
+	dist) ${EZ_COMMAND_DOT_DISTRIBUTE} "${command_args}" ;;
+	update) ${EZ_COMMAND_DOT_UPDATE} "${command_args}" ;;
+	-h | --help)
+		usage
+		exit $BASH_EX_OK
+		;;
+	-V | --version)
+		echo "${SCRIPT_NAME} ${EZ_DOT_VERSION}"
+		exit $BASH_EX_OK
+		;;
+	*)
+		usage
+		error "Command '${command}' not found" $BASH_EZ_EX_COMMAND_NOTFOUND
+		;;
+	esac
 }
 
 ############################################################# MAIN EXECUTION ###
 
-function _main () {
-  script_vars
-  handle_args "$@"
-  return $?
+function _main() {
+	script_vars
+	handle_args "$@"
+	return $?
 }
-
 
 res=0
 _main "$@"
diff --git a/dot/utils/detect b/dot/utils/detect
--- a/dot/utils/detect
+++ b/dot/utils/detect
@@ -35,26 +35,22 @@
 # Date   : 2020-08-14
 ################################################################################
 
-
 if [ "${0##*/}" == "${BASH_SOURCE[0]##*/}" ]; then
-  echo "WARNING: $(realpath -s $0) is not meant to be executed directly!" >&2;
-  echo "Use this script only by sourcing it." >&2;
-  exit 1
+	echo "WARNING: $(realpath -s $0) is not meant to be executed directly!" >&2
+	echo "Use this script only by sourcing it." >&2
+	exit 1
 fi
 
 # Header guard
-[[ -z "${GENERATE_GENERATE_SH_INCLUDED+x}" ]] \
-  && readonly GENERATE_GENERATE_SH_INCLUDED=1 \
-  || return 0
-
+[[ -z "${GENERATE_GENERATE_SH_INCLUDED+x}" ]] &&
+	readonly GENERATE_GENERATE_SH_INCLUDED=1 ||
+	return 0
 
 source "$(dirname -- $(realpath -- "${BASH_SOURCE[0]}"))/../../.ez-installrc"
 source "${EZ_INSTALL_HOME}/common/include.sh"
 
-
 include "${EZ_INSTALL_HOME}/common/array.sh"
 include "${EZ_INSTALL_HOME}/common/string.sh"
-
 
 # TODO: Make bidirectional
 #       Make diffing changes detect the most recent file
@@ -75,115 +71,114 @@ include "${EZ_INSTALL_HOME}/common/string.sh"
 #
 # Returns $3, $4, $5 variable args with new values from execution.
 function detect_change() {
-  local __source=$1
-  local __target=$2
-  local __changes_list=$3
-  local __changes_count=$4
-  local __total_files_count=$5
-  local silent=$6
+	local __source=$1
+	local __target=$2
+	local __changes_list=$3
+	local __changes_count=$4
+	local __total_files_count=$5
+	local silent=$6
 
-  # Check args count
-  if [[ $# -lt 3 ]]; then
-    echolog "${RED}${FUNCNAME[0]}: Invalid number of arguments${NC}"
-    return 1
-  fi
+	# Check args count
+	if [[ $# -lt 3 ]]; then
+		echolog "${RED}${FUNCNAME[0]}: Invalid number of arguments${NC}"
+		return 1
+	fi
 
-  # Exit if invalid path
-  if [[ ! -e "${__source}" ]]; then
-    error "${SCRIPTPATH} ${FUNCNAME[0]}: Invalid source path '${__source}'"
-    return 2
-  fi
+	# Exit if invalid path
+	if [[ ! -e "${__source}" ]]; then
+		error "${SCRIPTPATH} ${FUNCNAME[0]}: Invalid source path '${__source}'"
+		return 2
+	fi
 
-  local __tmp_changes_list
-  local __tmp_changes_count
-  local __tmp_total_files_count
+	local __tmp_changes_list
+	local __tmp_changes_count
+	local __tmp_total_files_count
 
-  # Strip all trailing backslashes '/'
-  __source=$(echo "${__source}" | sed 's,/*$,,')
-  __target=$(echo "${__target}" | sed 's,/*$,,')
+	# Strip all trailing backslashes '/'
+	__source=$(echo "${__source}" | sed 's,/*$,,')
+	__target=$(echo "${__target}" | sed 's,/*$,,')
 
-  if [[ -d "${__source}" ]]; then # Directory dotfile
-    # Recursively compare
-    while IFS= read -r -d '' __source_file; do
-      # Strip all trailing backslashes '/'
-      __source_file=$(echo "${__source_file}" | sed 's,/*$,,')
-      # Get relative path to append to target
-      __rel_path_file=$(echo "${__source_file}" | sed "s,${__source}/,,")
-      __target_file="${__target}/${__rel_path_file}"
+	if [[ -d "${__source}" ]]; then # Directory dotfile
+		# Recursively compare
+		while IFS= read -r -d '' __source_file; do
+			# Strip all trailing backslashes '/'
+			__source_file=$(echo "${__source_file}" | sed 's,/*$,,')
+			# Get relative path to append to target
+			__rel_path_file=$(echo "${__source_file}" | sed "s,${__source}/,,")
+			__target_file="${__target}/${__rel_path_file}"
 
-      # Ignore if in DOTFILES_IGNORE_LIST
-      if array_has_element "${__source_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
-        printf "${FG_LT_BLACK}Changes ignored ${__source_file}${ANSI_OFF}\n"
-        continue
-      fi
-      if array_has_element "${__target_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
-        printf "${FG_LT_BLACK}Changes ignored ${__target_file}${ANSI_OFF}\n"
-        continue
-      fi
+			# Ignore if in DOTFILES_IGNORE_LIST
+			if array_has_element "${__source_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
+				printf "${FG_LT_BLACK}Changes ignored ${__source_file}${ANSI_OFF}\n"
+				continue
+			fi
+			if array_has_element "${__target_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
+				printf "${FG_LT_BLACK}Changes ignored ${__target_file}${ANSI_OFF}\n"
+				continue
+			fi
 
-      # Compare dotfiles in target dir with local copy in source dir
-      if cmp "${__source_file}" "${__target_file}" &> /dev/null; then
-        if [[ ${silent} -ne 1 ]]; then
-          echolog "No changes detected in ${__source_file}"
-        else
-          log "No changes detected in ${__source_file}"
-        fi
-      else
-        if [[ -e "${__target_file}" ]]; then
-          echolog "${YELLOW}Changes detected:${NC}" ${silent}
-          echolog "${BLUE}SOURCE ${__source_file}${NC}" ${silent}
-          echolog "${BLUE}TARGET ${__target_file}${NC}" ${silent}
-        else
-          echolog "${YELLOW}Missing file:${NC}" ${silent}
-          echolog "${BLUE}SOURCE ${__source_file}${NC}" ${silent}
-          echolog "${RED}TARGET ${__target_file}${NC}" ${silent}
-        fi
-        # Record changes
-        __tmp_changes_count=$(expr ${__tmp_changes_count} + 1)
-        if [[ -z "${__tmp_changes_list}" ]]; then
-          __tmp_changes_list="${__source_file};${__target_file}"
-        else
-          __tmp_changes_list="${__tmp_changes_list}\n${__source_file};${__target_file}"
-        fi
-      fi
-      # Increment total files compared
-      __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
-    done < <(find "${__source}" -not -path "*/.git/*" -type f -print0) # Process substitution for outside variables
-  else # Non-directory dotfile
-    # Compare dotfiles in target dir with local copy in source dir
-    if cmp -s "${__source}" "${__target}" &> /dev/null; then
-      if [[ ${silent} -ne 1 ]]; then
-        echolog "No changes detected in ${__source}"
-      else
-        log "No changes detected in ${__source}"
-      fi
-    else
-      if [[ -e "${__target}" ]]; then
-        echolog "${YELLOW}Changes detected:${NC}" ${silent}
-        echolog "${BLUE}SOURCE ${__source}${NC}" ${silent}
-        echolog "${BLUE}TARGET ${__target}${NC}" ${silent}
-      else
-        echolog "${YELLOW}Missing file:${NC}" ${silent}
-        echolog "${BLUE}SOURCE ${__source}${NC}" ${silent}
-        echolog "${RED}TARGET ${__target}${NC}" ${silent}
-      fi
-      # Record changes
-      __tmp_changes_count=$(expr ${__tmp_changes_count} + 1)
-      if [[ -z "${__tmp_changes_list}" ]]; then
-        __tmp_changes_list="${__source};${__target}"
-      else
-        __tmp_changes_list="${__tmp_changes_list}\n${__source};${__target}"
-      fi
-    fi
-    # Increment total files compared
-    __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
-  fi
-  # Return variables
-  [[ -n "${__changes_list}" ]]      && eval $__changes_list="'$__tmp_changes_list'"
-  [[ -n "${__changes_count}" ]]     && eval $__changes_count=$__tmp_changes_count
-  [[ -n "${__total_files_count}" ]] && eval $__total_files_count=$__tmp_total_files_count
+			# Compare dotfiles in target dir with local copy in source dir
+			if cmp "${__source_file}" "${__target_file}" &>/dev/null; then
+				if [[ ${silent} -ne 1 ]]; then
+					echolog "No changes detected in ${__source_file}"
+				else
+					log "No changes detected in ${__source_file}"
+				fi
+			else
+				if [[ -e "${__target_file}" ]]; then
+					echolog "${YELLOW}Changes detected:${NC}" ${silent}
+					echolog "${BLUE}SOURCE ${__source_file}${NC}" ${silent}
+					echolog "${BLUE}TARGET ${__target_file}${NC}" ${silent}
+				else
+					echolog "${YELLOW}Missing file:${NC}" ${silent}
+					echolog "${BLUE}SOURCE ${__source_file}${NC}" ${silent}
+					echolog "${RED}TARGET ${__target_file}${NC}" ${silent}
+				fi
+				# Record changes
+				__tmp_changes_count=$(expr ${__tmp_changes_count} + 1)
+				if [[ -z "${__tmp_changes_list}" ]]; then
+					__tmp_changes_list="${__source_file};${__target_file}"
+				else
+					__tmp_changes_list="${__tmp_changes_list}\n${__source_file};${__target_file}"
+				fi
+			fi
+			# Increment total files compared
+			__tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
+		done < <(find "${__source}" -not -path "*/.git/*" -type f -print0) # Process substitution for outside variables
+	else                                                                # Non-directory dotfile
+		# Compare dotfiles in target dir with local copy in source dir
+		if cmp -s "${__source}" "${__target}" &>/dev/null; then
+			if [[ ${silent} -ne 1 ]]; then
+				echolog "No changes detected in ${__source}"
+			else
+				log "No changes detected in ${__source}"
+			fi
+		else
+			if [[ -e "${__target}" ]]; then
+				echolog "${YELLOW}Changes detected:${NC}" ${silent}
+				echolog "${BLUE}SOURCE ${__source}${NC}" ${silent}
+				echolog "${BLUE}TARGET ${__target}${NC}" ${silent}
+			else
+				echolog "${YELLOW}Missing file:${NC}" ${silent}
+				echolog "${BLUE}SOURCE ${__source}${NC}" ${silent}
+				echolog "${RED}TARGET ${__target}${NC}" ${silent}
+			fi
+			# Record changes
+			__tmp_changes_count=$(expr ${__tmp_changes_count} + 1)
+			if [[ -z "${__tmp_changes_list}" ]]; then
+				__tmp_changes_list="${__source};${__target}"
+			else
+				__tmp_changes_list="${__tmp_changes_list}\n${__source};${__target}"
+			fi
+		fi
+		# Increment total files compared
+		__tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
+	fi
+	# Return variables
+	[[ -n "${__changes_list}" ]] && eval $__changes_list="'$__tmp_changes_list'"
+	[[ -n "${__changes_count}" ]] && eval $__changes_count=$__tmp_changes_count
+	[[ -n "${__total_files_count}" ]] && eval $__total_files_count=$__tmp_total_files_count
 }
-
 
 # Compares two file path (would compare recursively if files are directories)
 # and returns all files that does not exists in the target file or directory.
@@ -199,83 +194,82 @@ function detect_change() {
 #
 # Returns $3, $4, $5 variable args with new values from execution.
 detect_delete() {
-  local __source=$1
-  local __target=$2
-  local __deletion_list=$3
-  local __deletion_count=$4
-  local __total_files_count=$5
-  local silent=$6
+	local __source=$1
+	local __target=$2
+	local __deletion_list=$3
+	local __deletion_count=$4
+	local __total_files_count=$5
+	local silent=$6
 
-  # Check args count
-  if [[ $# -lt 3 ]]; then
-    echolog "${RED}${FUNCNAME[0]}: Invalid number of arguments${NC}"
-    return 1
-  fi
+	# Check args count
+	if [[ $# -lt 3 ]]; then
+		echolog "${RED}${FUNCNAME[0]}: Invalid number of arguments${NC}"
+		return 1
+	fi
 
-  local __tmp_deletion_list
-  local __tmp_deletion_count
-  local __tmp_total_files_count
+	local __tmp_deletion_list
+	local __tmp_deletion_count
+	local __tmp_total_files_count
 
-  # Strip all trailing backslashes '/'
-  __source=$(echo "${__source}" | sed 's,/*$,,')
-  __target=$(echo "${__target}" | sed 's,/*$,,')
+	# Strip all trailing backslashes '/'
+	__source=$(echo "${__source}" | sed 's,/*$,,')
+	__target=$(echo "${__target}" | sed 's,/*$,,')
 
-  if [[ -d "${__source}" ]]; then # Directory dotfile
-    # Recursively compare
-    while IFS= read -r -d '' __source_file; do
-      # Strip all trailing backslashes '/'
-      __source_file=$(echo "${__source_file}" | sed 's,/*$,,')
-      # Get relative path to append to target
-      __rel_path_file=$(echo "${__source_file}" | sed "s,${__source}/,,")
-      __target_file="${__target}/${__rel_path_file}"
+	if [[ -d "${__source}" ]]; then # Directory dotfile
+		# Recursively compare
+		while IFS= read -r -d '' __source_file; do
+			# Strip all trailing backslashes '/'
+			__source_file=$(echo "${__source_file}" | sed 's,/*$,,')
+			# Get relative path to append to target
+			__rel_path_file=$(echo "${__source_file}" | sed "s,${__source}/,,")
+			__target_file="${__target}/${__rel_path_file}"
 
-      # Ignore if in DOTFILES_IGNORE_LIST
-      if array_has_element "${__source_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
-        printf "${FG_LT_BLACK}Deletion ignored ${__source_file}${ANSI_OFF}\n"
-        continue
-      fi
-      if array_has_element "${__target_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
-        printf "${FG_LT_BLACK}Deletion ignored ${__target_file}${ANSI_OFF}\n"
-        continue
-      fi
+			# Ignore if in DOTFILES_IGNORE_LIST
+			if array_has_element "${__source_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
+				printf "${FG_LT_BLACK}Deletion ignored ${__source_file}${ANSI_OFF}\n"
+				continue
+			fi
+			if array_has_element "${__target_file}" "${DOTFILES_IGNORE_LIST[@]}"; then
+				printf "${FG_LT_BLACK}Deletion ignored ${__target_file}${ANSI_OFF}\n"
+				continue
+			fi
 
-      # Check deleted files
-      if [[ ! -e "${__target_file}" ]]; then
-        # Record deletion if not NO_DELETE
-        if [[ -z "${NO_DELETE}" ]]; then
-          echolog "${RED}File to be deleted ${__source_file}${NC}" ${silent}
-          __tmp_deletion_count=$(expr ${__tmp_deletion_count} + 1)
-        else
-          echolog "${RED}File to be deleted ${__source_file} ${YELLOW}SKIPPED${NC}" ${silent}
-        fi
-        # Append to changes list
-        if [[ -z ${__tmp_deletion_list} ]]; then
-          __tmp_deletion_list="${__source_file}"
-        else
-          __tmp_deletion_list="${__tmp_deletion_list}\n${__source_file}"
-        fi
-      fi
-      # Increment total files compared
-      __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
-    done < <(find "${__source}" -not -path "*/.git/*" -type f -print0) # Process substitution for outside variables
-  else # Non-directory dotfile
-    # Check deleted files
-    if [[ ! -e "${__target}" ]]; then
-      echolog "${RED}File does not exist ${__source}${NC}" ${silent}
-      # Record changes
-      __tmp_deletion_count=$(expr ${__tmp_deletion_count} + 1)
-      if [[ -z ${__tmp_deletion_list} ]]; then
-        __tmp_deletion_list="${__source}"
-      else
-        __tmp_deletion_list="${__tmp_deletion_list}\n${__source}"
-      fi
-    fi
-    # Increment total files compared
-    __tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
-  fi
-  # Return variables
-  [[ -n "${__deletion_list}" ]]     && eval $__deletion_list="'$__tmp_deletion_list'"
-  [[ -n "${__deletion_count}" ]]    && eval $__deletion_count=$__tmp_deletion_count
-  [[ -n "${__total_files_count}" ]] && eval $__total_files_count=$__tmp_total_files_count
+			# Check deleted files
+			if [[ ! -e "${__target_file}" ]]; then
+				# Record deletion if not NO_DELETE
+				if [[ -z "${NO_DELETE}" ]]; then
+					echolog "${RED}File to be deleted ${__source_file}${NC}" ${silent}
+					__tmp_deletion_count=$(expr ${__tmp_deletion_count} + 1)
+				else
+					echolog "${RED}File to be deleted ${__source_file} ${YELLOW}SKIPPED${NC}" ${silent}
+				fi
+				# Append to changes list
+				if [[ -z ${__tmp_deletion_list} ]]; then
+					__tmp_deletion_list="${__source_file}"
+				else
+					__tmp_deletion_list="${__tmp_deletion_list}\n${__source_file}"
+				fi
+			fi
+			# Increment total files compared
+			__tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
+		done < <(find "${__source}" -not -path "*/.git/*" -type f -print0) # Process substitution for outside variables
+	else                                                                # Non-directory dotfile
+		# Check deleted files
+		if [[ ! -e "${__target}" ]]; then
+			echolog "${RED}File does not exist ${__source}${NC}" ${silent}
+			# Record changes
+			__tmp_deletion_count=$(expr ${__tmp_deletion_count} + 1)
+			if [[ -z ${__tmp_deletion_list} ]]; then
+				__tmp_deletion_list="${__source}"
+			else
+				__tmp_deletion_list="${__tmp_deletion_list}\n${__source}"
+			fi
+		fi
+		# Increment total files compared
+		__tmp_total_files_count=$(expr ${__tmp_total_files_count} + 1)
+	fi
+	# Return variables
+	[[ -n "${__deletion_list}" ]] && eval $__deletion_list="'$__tmp_deletion_list'"
+	[[ -n "${__deletion_count}" ]] && eval $__deletion_count=$__tmp_deletion_count
+	[[ -n "${__total_files_count}" ]] && eval $__total_files_count=$__tmp_total_files_count
 }
-
diff --git a/ez b/ez
--- a/ez
+++ b/ez
@@ -17,80 +17,96 @@ include "${EZ_INSTALL_HOME}/actions.sh"
 ################################################## CONSTANT GLOBAL VARIABLES ###
 
 readonly EZ_VERSION="0.3 BETA"
-readonly SCRIPT_ARGS=( "${@}" )
+readonly SCRIPT_ARGS=("${@}")
 
 ############################################################### FLAG OPTIONS ###
 
 function usage() {
-  print_page "${EZ_INSTALL_HOME}/man/ez_usage"
+	print_page "${EZ_INSTALL_HOME}/man/ez_usage"
 }
-
 
 # TODO: Auto generate exit codes.
-function manual () {
-  ${EZ_COMMAND_INSTALL} -h
-  ${EZ_COMMAND_GEN} -h
-  print_page "${EZ_INSTALL_HOME}/man/ez_manual"
+function manual() {
+	${EZ_COMMAND_INSTALL} -h
+	${EZ_COMMAND_GEN} -h
+	print_page "${EZ_INSTALL_HOME}/man/ez_manual"
 }
 
-
 function handle_args() {
-  # Disallow piped cli args
-  if [[ -p /dev/stdin ]];             then usage; error "Piped arguments not supported" "$BASH_SYS_EX_USAGE"; fi
-  # Disallow Stdin redirection
-  if [[ ! -t 0 && ! -p /dev/stdin ]]; then usage; error "Stdin redirection not supported" "$BASH_SYS_EX_USAGE"; fi
-  # Require arguments
-  if [[ -z "${1+x}" ]];               then usage; error "${BASH_SYS_MSG_USAGE_MISSARG}" "$BASH_SYS_EX_USAGE"; fi
+	# Disallow piped cli args
+	if [[ -p /dev/stdin ]]; then
+		usage
+		error "Piped arguments not supported" "$BASH_SYS_EX_USAGE"
+	fi
+	# Disallow Stdin redirection
+	if [[ ! -t 0 && ! -p /dev/stdin ]]; then
+		usage
+		error "Stdin redirection not supported" "$BASH_SYS_EX_USAGE"
+	fi
+	# Require arguments
+	if [[ -z "${1+x}" ]]; then
+		usage
+		error "${BASH_SYS_MSG_USAGE_MISSARG}" "$BASH_SYS_EX_USAGE"
+	fi
 
-  # Catch command and throw it away to focus on the rest of args to pass to the command execution
-  local command="${1}"
-  shift 1
+	# Catch command and throw it away to focus on the rest of args to pass to the command execution
+	local command="${1}"
+	shift 1
 
-  # Ref: https://stackoverflow.com/a/1669493
-  # Transform args to string to quote OPTARG with whitespace.
-  # WARNING: Receiving end needs to use `eval set -- "${@:-}"`
-  local command_args=""
-  for i in "$@"; do
-    if [[ $i =~ ^--.*= ]]; then
-      i="$(sed -e "s/\(--.*=\)\(.*\)/\1'\2'/" <<< "$i")"
-    elif [[ $i =~ [[:space:]] ]]; then
-      i="'$i'"
-    fi
-    command_args="${command_args} $i"
-  done
+	# Ref: https://stackoverflow.com/a/1669493
+	# Transform args to string to quote OPTARG with whitespace.
+	# WARNING: Receiving end needs to use `eval set -- "${@:-}"`
+	local command_args=""
+	for i in "$@"; do
+		if [[ $i =~ ^--.*= ]]; then
+			i="$(sed -e "s/\(--.*=\)\(.*\)/\1'\2'/" <<<"$i")"
+		elif [[ $i =~ [[:space:]] ]]; then
+			i="'$i'"
+		fi
+		command_args="${command_args} $i"
+	done
 
-  case "${command}" in
-    dot)            ${EZ_COMMAND_DOT}     "${command_args}" ;;
-    gen)            ${EZ_COMMAND_GEN}     "${command_args}" ;;
-    install)        ${EZ_COMMAND_INSTALL} "${command_args}" ;;
-    -h|--help)      usage; manual; exit "$BASH_EX_OK" ;;
-    -V|--version)   echo "${SCRIPT_NAME} ${EZ_VERSION}"; exit "$BASH_EX_OK" ;;
-    *)
-      usage
-      error "Command '${1}' not found" "$BASH_EZ_EX_COMMAND_NOTFOUND"
-  esac
+	case "${command}" in
+	dot) ${EZ_COMMAND_DOT} "${command_args}" ;;
+	gen) ${EZ_COMMAND_GEN} "${command_args}" ;;
+	install) ${EZ_COMMAND_INSTALL} "${command_args}" ;;
+	-h | --help)
+		usage
+		manual
+		exit "$BASH_EX_OK"
+		;;
+	-V | --version)
+		echo "${SCRIPT_NAME} ${EZ_VERSION}"
+		exit "$BASH_EX_OK"
+		;;
+	*)
+		usage
+		error "Command '${1}' not found" "$BASH_EZ_EX_COMMAND_NOTFOUND"
+		;;
+	esac
 }
 
 ###################################################################### UTILS ###
 
 function _ctrl_c() {
-  if "${DEBUG}"; then
-    echo ""
-    log 'error' "$(basename -- "${BASH_SOURCE[1]}").${FUNCNAME[1]}(): Interrupted!" "$BASH_EX_TERMCTRLC"
-  fi
+	if "${DEBUG}"; then
+		echo ""
+		log 'error' "$(basename -- "${BASH_SOURCE[1]}").${FUNCNAME[1]}(): Interrupted!" "$BASH_EX_TERMCTRLC"
+	fi
 }
 
 ############################################################# MAIN EXECUTION ###
 
-function _main () {
-  # Set up trap
-  trap _ctrl_c INT TERM
+function _main() {
+	# Set up trap
+	trap _ctrl_c INT TERM
 
-  script_vars
-  handle_args "$@"
-  return $?
+	script_vars
+	handle_args "$@"
+	return $?
 }
 
-
-res=0; _main "${SCRIPT_ARGS[@]}"; res=$?
+res=0
+_main "${SCRIPT_ARGS[@]}"
+res=$?
 exit $res
